import type { components } from "@/api/schema"

type S = components["schemas"]

export type ApiJsonValue = S["JsonValue"]
export type ApiJsonObject = S["JsonObject"]
export type ApiJsonSchema = S["JsonSchema"]
export type ApiProblemRow = S["Problem"]
export type ApiErrorCode = S["ApiErrorCode"]

export type ApiReady = S["ReadyState"]
export type ApiProject = S["ProjectInfo"]
export type ApiIndexState = S["IndexState"]
export type ApiProblemCounts = S["ProblemCounts"]
export type ApiFileRef = S["FileRef"]
export type ApiFileEntry = S["FileEntry"]
export type ApiFileDetail = S["FileDetail"]
export type ApiFileKind = S["FileKind"]
export type ApiDiagnostic = S["Diagnostic"]

export type ApiFlow = S["FlowSummary"]
export type ApiFlowDetail = S["FlowDetail"]
export type ApiFlowSpec = S["FlowSpecView"]
export type ApiFlowIr = S["FlowIr"]
export type ApiFlowSchemas = S["FlowSchemas"]
export type ApiRunBrief = S["RunBrief"]
export type ApiDatasetSummary = S["DatasetSummary"]
export type ApiDatasetCase = S["DatasetCase"]
export type ApiDatasetFile = S["DatasetFile"]
export type ApiDatasetCreateRequest = S["DatasetCreateRequest"]
export type ApiDatasetBatch = S["DatasetBatchRecord"]
export type ApiDatasetBatchCase = S["DatasetBatchCase"]
export type ApiDatasetBatchStartRequest = S["DatasetBatchStartRequest"]
export type ApiRunScopePreview = S["RunScopePreview"]
export type ApiDatasetRangePreview = S["DatasetRangePreview"]
export type ApiDatasetRangePair = S["DatasetRangePair"]
export type ApiManualRangePreview = S["ManualRangePreview"]
export type ApiManualRangePair = S["ManualRangePair"]

export type ApiNode = S["NodeSummary"]
export type ApiNodeDetail = S["NodeDetail"]
export type ApiNodeCode = S["NodeCode"]
export type ApiNodeSchemas = S["NodeSchemas"]
export type ApiBinding = S["CompiledBinding"]

export type ApiPrompt = S["PromptSummary"]
export type ApiPromptDetail = S["PromptDetail"]
export type ApiPromptPreview = S["PromptPreview"]
export type ApiPromptPreviewBody = S["PromptPreviewBody"]
export type ApiPromptSlot = S["PromptSlot"]
export type ApiSlotProvenance = S["SlotProvenance"]

export type ApiRun = S["RunSummary"]
export type ApiRunSnapshot = S["RunSnapshot"]
export type ApiRunStartRequest = S["RunStartRequest"]
export type ApiRunStarted = S["RunStarted"]
export type ApiRunError = S["RunError"]
export type ApiRunEvent = S["RunEvent"]
export type ApiNodeCounts = S["NodeCounts"]
export type ApiLineage = S["Lineage"]
export type ApiSpecVersion = S["SpecVersionInfo"]

export type ApiExecution = S["NodeExecution"]
export type ApiExecutionDetail = S["ExecutionDetail"]
export type ApiExecutionAddress = S["ExecutionAddress"]
export type ApiIncludePayloads = S["IncludePayloads"]
export type ApiAttempt = S["Attempt"]
export type ApiCheckOutcome = S["CheckOutcome"]

export type ApiHumanWait = S["HumanWait"]
export type ApiHumanWaitDetail = S["HumanWaitDetail"]
export type ApiHumanWaitAttempt = S["HumanWaitAttempt"]
export type ApiIgnoredAnswer = S["IgnoredAnswer"]
export type ApiResumeRequest = S["ResumeRequest"]
export type ApiResumeResult = S["ResumeResult"]
export type ApiForkRequest = S["ForkRequest"]
export type ApiRunForked = S["RunForked"]
export type ApiCancelResult = S["CancelResult"]

export type ApiValueRef = S["ValueRef"]
export type ApiInlineValue = S["InlineValue"]
export type ApiMediaValue = S["MediaValue"]
export type ApiBlobValue = S["BlobValue"]
export type ApiBlobMeta = S["BlobMeta"]
export type ApiBlobUploaded = S["BlobUploaded"]

export type ApiType = S["TypeSummary"]
export type ApiTypeDetail = S["TypeDetail"]

export type ApiSetting = S["SettingView"]
export type ApiSettingWrite = S["SettingWrite"]
export type ApiSettingDeleted = S["SettingDeleted"]
export type ApiProviderKey = S["ProviderKeyStatus"]
export type ApiSecret = S["SecretStatus"]
export type ApiSecretScope = S["SecretScope"]

export type ApiChatStatus = S["LoginStatus"]
export type ApiChatBackendKind = S["AgentBackendKind"]
export type ApiChatBackendChoice = S["ChatBackendChoice"]
export type ApiChatBackendWrite = S["ChatBackendWrite"]
export type ApiChatSession = S["ChatSession"]
export type ApiChatSessionCreate = S["ChatSessionCreate"]
export type ApiChatModelCatalog = S["ChatModelCatalog"]
export type ApiChatSessionSettings = S["ChatSessionSettings"]
export type ApiChatModel = S["ChatModel"]
export type ApiChatEffort = S["ChatEffort"]
export type ApiChatPermissionMode = S["ChatPermissionMode"]
export type ApiChatMessageRequest = S["ChatMessageRequest"]
export type ApiChatTurnAccepted = S["ChatTurnAccepted"]
export type ApiChatApprovalReply = S["ChatApprovalReply"]
export type ApiChatEvent = S["ChatEvent"]

export type ApiSpecEvent = S["SpecEvent"]
