import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Final

import pytest

from aqven.check import CheckReport, check_project
from aqven.cli import main
from aqven.codegen import GENERATED_HEADER, GENERATED_TYPES, TYPES_PACKAGE_INIT, generate_types
from aqven.diagnostics import Diagnostic, DiagnosticCode, Severity
from aqven.testing import copy_project

FIXTURE: Final = Path(__file__).parent / "fixtures" / "standard_shop"
HEADER_LINE: Final = (
    "# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate."
)
EDITED_HINT: Final = "this file is generated, edits are overwritten, change the YAML source"
IMPORT_PROBE: Final = """import json
import sys
import types

sys.path.insert(0, sys.argv[1])
import standard_shop.types as generated

print(json.dumps({
    "generated": generated.__file__,
    "stdlib": types.__file__,
    "note": generated.Note.__name__,
    "folder_has_init": hasattr(generated, "__path__"),
}))
"""


@pytest.fixture
def shop(tmp_path: Path) -> Path:
    return copy_project(FIXTURE, tmp_path)


def of_code(report: CheckReport, code: DiagnosticCode) -> list[Diagnostic]:
    return [item for item in report.diagnostics if item.code is code]


def test_generated_file_sits_at_the_module_root_and_starts_with_the_header() -> None:
    lines = (FIXTURE / GENERATED_TYPES).read_text(encoding="utf-8").splitlines()

    assert GENERATED_TYPES == "types.py"
    assert GENERATED_HEADER == HEADER_LINE
    assert lines[0] == HEADER_LINE
    assert (FIXTURE / "types").is_dir()
    assert not (FIXTURE / TYPES_PACKAGE_INIT).exists()


def test_package_types_imports_the_generated_file_next_to_the_types_folder(tmp_path: Path) -> None:
    completed = subprocess.run(
        [sys.executable, "-c", IMPORT_PROBE, str(FIXTURE.parent)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )

    assert completed.returncode == 0, completed.stderr
    probe = json.loads(completed.stdout)
    assert Path(probe["generated"]) == FIXTURE / GENERATED_TYPES
    assert Path(probe["stdlib"]).parent != FIXTURE
    assert probe["note"] == "Note"
    assert probe["folder_has_init"] is False


def test_hand_edit_of_the_generated_file_is_reported_until_generate(
    shop: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    target = shop / GENERATED_TYPES
    target.write_text(target.read_text(encoding="utf-8") + "\n\nEXTRA = 1\n", encoding="utf-8")

    stale = of_code(check_project(shop), DiagnosticCode.W_GENERATED_STALE)

    assert [(item.file, item.severity) for item in stale] == [(GENERATED_TYPES, Severity.WARNING)]
    assert EDITED_HINT in stale[0].message
    assert stale[0].hint == "change the YAML source and run aqven generate"
    assert main(["generate", str(shop)]) == 0
    assert capsys.readouterr().out.strip() == GENERATED_TYPES
    assert "EXTRA" not in target.read_text(encoding="utf-8")
    assert check_project(shop).diagnostics == ()


def test_missing_generated_file_asks_to_run_generate(shop: Path) -> None:
    (shop / GENERATED_TYPES).unlink()

    stale = of_code(check_project(shop), DiagnosticCode.W_GENERATED_STALE)

    assert [item.file for item in stale] == [GENERATED_TYPES]
    assert "is missing" in stale[0].message
    assert stale[0].hint == "run aqven generate to write types.py"


def test_types_package_init_is_an_error_because_it_shadows_the_generated_file(shop: Path) -> None:
    (shop / TYPES_PACKAGE_INIT).write_text("", encoding="utf-8")

    report = check_project(shop)
    shadowed = of_code(report, DiagnosticCode.E_TYPES_PACKAGE)

    assert [(item.file, item.severity) for item in shadowed] == [(TYPES_PACKAGE_INIT, Severity.ERROR)]
    assert "shadows the generated types.py" in shadowed[0].message
    assert shadowed[0].hint is not None
    assert shadowed[0].hint.startswith(f"delete {TYPES_PACKAGE_INIT}:")
    assert "standard_shop.types" in shadowed[0].hint
    assert not report.ok


@pytest.mark.parametrize(("on_sys_path", "on_pythonpath"), [(True, False), (False, True), (True, True)])
def test_module_folder_on_the_python_path_is_a_warning(
    shop: Path, monkeypatch: pytest.MonkeyPatch, on_sys_path: bool, on_pythonpath: bool
) -> None:
    monkeypatch.setattr(sys, "path", [*sys.path, *([str(shop)] if on_sys_path else [])])
    pythonpath = [str(shop.parent / "elsewhere"), *([str(shop)] if on_pythonpath else [])]
    monkeypatch.setenv("PYTHONPATH", os.pathsep.join(pythonpath))

    warned = of_code(check_project(shop), DiagnosticCode.W_TYPES_SHADOWS_STDLIB)

    assert [(item.file, item.severity) for item in warned] == [(GENERATED_TYPES, Severity.WARNING)]
    assert "standard library module types" in warned[0].message
    assert os.path.realpath(shop) in warned[0].message
    assert warned[0].hint is not None
    assert "PYTHONPATH" in warned[0].hint
    assert "standard_shop.types" in warned[0].hint


def test_current_folder_entry_resolves_to_the_module_folder(shop: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(shop)
    monkeypatch.setattr(sys, "path", [*sys.path, ""])
    monkeypatch.delenv("PYTHONPATH", raising=False)

    assert [item.file for item in of_code(check_project(shop), DiagnosticCode.W_TYPES_SHADOWS_STDLIB)] == [
        GENERATED_TYPES
    ]


def test_parent_folder_on_the_path_is_not_a_warning(shop: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(sys, "path", [*sys.path, str(shop.parent)])
    monkeypatch.setenv("PYTHONPATH", str(shop.parent))

    assert of_code(check_project(shop), DiagnosticCode.W_TYPES_SHADOWS_STDLIB) == []


def test_generate_removes_the_file_when_nothing_is_declared(tmp_path: Path) -> None:
    root = tmp_path / "empty_shop"
    root.mkdir()
    project = (FIXTURE / "aqven.yaml").read_text(encoding="utf-8")
    (root / "aqven.yaml").write_text(project.replace('"standard_shop"', '"empty_shop"'), encoding="utf-8")
    (root / GENERATED_TYPES).write_text(f"{HEADER_LINE}\nLEFTOVER = 1\n", encoding="utf-8")

    assert generate_types(root).project is not None
    assert not (root / GENERATED_TYPES).exists()
    assert of_code(check_project(root), DiagnosticCode.W_GENERATED_STALE) == []
