import json
import keyword
from collections.abc import Callable, Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from types import MappingProxyType
from typing import Final, assert_never

from pydantic import BaseModel

from aqven.loader import LoadedFlow, LoadedProject, LoadResult, load_project, local_node_id
from aqven.spec import (
    AUDIO,
    BOOL,
    DATE,
    DATE_TIME,
    DOCUMENT,
    DYNAMIC,
    FIELD_SPEC,
    FLOAT,
    IMAGE,
    INT,
    LOCALE,
    MAP_ITEM_ERROR,
    TENANT_ID,
    TEXT,
    TIME_ZONE,
    VIDEO,
    ArmId,
    CodeNodeSpec,
    Constraints,
    EnumType,
    ExperimentId,
    FieldDecl,
    FlowId,
    IdType,
    InferenceId,
    InferenceSpec,
    NodeId,
    RecordType,
    ToolId,
    ToolSpec,
    TypeId,
    TypeModelError,
    TypeModels,
    TypeSpec,
    UnionType,
    UnionVariant,
    ValueType,
    build_type_models,
    parse_type_ref,
)

GENERATED_TYPES: Final = "types.py"
GENERATED_MODULE: Final = "types"
GENERATED_HEADER: Final = (
    "# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate."
)
TYPES_PACKAGE_INIT: Final = "types/__init__.py"
ID_FIELD_SUFFIX: Final = "Field"
BLOCK_SEPARATOR: Final = "\n\n\n"
IMPORT_SEPARATOR: Final = "\n\n"
CLASS_PREFIX: Final = "class "
RESERVED_NAMES: Final = frozenset({*dir(BaseModel), *keyword.kwlist})
IMPORT_GROUPS: Final = (("datetime", "typing"), ("pydantic",), ("aqven.spec",))
INPUT_SUFFIX: Final = "In"
OUTPUT_SUFFIX: Final = "Out"
type StepKey = tuple[FlowId, NodeId]
type ArmStepKey = tuple[ExperimentId, ArmId, NodeId]

NO_INFERENCES: Final[Mapping[InferenceId, InferenceSpec]] = MappingProxyType[InferenceId, InferenceSpec]({})
NO_TOOLS: Final[Mapping[ToolId, ToolSpec]] = MappingProxyType[ToolId, ToolSpec]({})
NO_STEPS: Final[Mapping[StepKey, CodeNodeSpec]] = MappingProxyType[StepKey, CodeNodeSpec]({})
NO_ARM_STEPS: Final[Mapping[ArmStepKey, CodeNodeSpec]] = MappingProxyType[ArmStepKey, CodeNodeSpec]({})

BUILTIN_NAMES: Final[Mapping[TypeId, tuple[str, str]]] = {
    TEXT: ("", "str"),
    INT: ("", "int"),
    FLOAT: ("", "float"),
    BOOL: ("", "bool"),
    DATE: ("datetime", "date"),
    DATE_TIME: ("datetime", "datetime"),
    TIME_ZONE: ("aqven.spec", "TimeZone"),
    LOCALE: ("aqven.spec", "Locale"),
    TENANT_ID: ("aqven.spec", "TenantId"),
    IMAGE: ("aqven.spec", "Image"),
    AUDIO: ("aqven.spec", "Audio"),
    VIDEO: ("aqven.spec", "Video"),
    DOCUMENT: ("aqven.spec", "Document"),
    DYNAMIC: ("aqven.spec", "DynamicValue"),
    FIELD_SPEC: ("aqven.spec", "FieldSpec"),
    MAP_ITEM_ERROR: ("aqven.spec", "MapItemError"),
}


@dataclass(frozen=True, slots=True)
class InferenceShape:
    inference_id: InferenceId

    @property
    def stem(self) -> str:
        return _pascal(self.inference_id)


@dataclass(frozen=True, slots=True)
class ToolShape:
    tool_id: ToolId

    @property
    def stem(self) -> str:
        return _pascal(self.tool_id)


@dataclass(frozen=True, slots=True)
class StepShape:
    flow_id: FlowId
    node_id: NodeId

    @property
    def stem(self) -> str:
        return f"{_pascal(self.flow_id)}{_pascal(local_node_id(self.node_id))}"


@dataclass(frozen=True, slots=True)
class ArmStepShape:
    experiment_id: ExperimentId
    arm_id: ArmId
    node_id: NodeId

    @property
    def stem(self) -> str:
        return f"{_pascal(self.experiment_id)}{_pascal(self.arm_id)}{_pascal(local_node_id(self.node_id))}"


type ShapeOwner = InferenceShape | ToolShape | StepShape | ArmStepShape


@dataclass(frozen=True, slots=True)
class ShapeRecord:
    name: str
    owner: ShapeOwner
    fields: Sequence[FieldDecl]


@dataclass(frozen=True, slots=True)
class GeneratedTypes:
    types: Mapping[TypeId, TypeSpec]
    records: tuple[ShapeRecord, ...]
    conflicts: tuple[ShapeRecord, ...]


def project_types(project: LoadedProject) -> Mapping[TypeId, TypeSpec]:
    return {type_id: source.spec for type_id, source in project.types.items()}


def project_inferences(project: LoadedProject) -> Mapping[InferenceId, InferenceSpec]:
    return {
        inference_id: source.spec
        for inference_id, loaded in project.inferences.items()
        if (source := loaded.source) is not None and loaded.builder_path is None
    }


def project_tools(project: LoadedProject) -> Mapping[ToolId, ToolSpec]:
    return {tool_id: source.spec for tool_id, source in project.tools.items()}


def project_steps(project: LoadedProject) -> Mapping[StepKey, CodeNodeSpec]:
    return {(flow_id, node_id): spec for flow_id, flow in project.flows.items() for node_id, spec in _code_steps(flow)}


def project_arm_steps(project: LoadedProject) -> Mapping[ArmStepKey, CodeNodeSpec]:
    return {
        (experiment_id, arm_id, node_id): spec
        for experiment_id, experiment in project.experiments.items()
        for arm_id, arm in experiment.arms.items()
        for node_id, spec in _code_steps(arm)
    }


def project_plan(project: LoadedProject) -> GeneratedTypes:
    return plan_types(
        project_types(project),
        project_inferences(project),
        project_tools(project),
        project_steps(project),
        project_arm_steps(project),
    )


def shape_records(
    owner: ShapeOwner, inputs: Sequence[FieldDecl], outputs: Sequence[FieldDecl]
) -> Iterator[ShapeRecord]:
    yield ShapeRecord(f"{owner.stem}{INPUT_SUFFIX}", owner, inputs)
    yield ShapeRecord(f"{owner.stem}{OUTPUT_SUFFIX}", owner, outputs)


def declared_records(
    inferences: Mapping[InferenceId, InferenceSpec],
    tools: Mapping[ToolId, ToolSpec],
    steps: Mapping[StepKey, CodeNodeSpec],
    arm_steps: Mapping[ArmStepKey, CodeNodeSpec] = NO_ARM_STEPS,
) -> Iterator[ShapeRecord]:
    for inference_id in sorted(inferences):
        spec = inferences[inference_id]
        yield from shape_records(InferenceShape(inference_id), spec.in_, spec.out)
    runnable = sorted(tool_id for tool_id, spec in tools.items() if spec.run is not None)
    for tool_id in runnable:
        tool = tools[tool_id]
        yield from shape_records(ToolShape(tool_id), tool.in_, tool.out)
    for key in sorted(steps):
        step = steps[key]
        yield from shape_records(StepShape(*key), step.in_, step.out)
    for key in sorted(arm_steps):
        step = arm_steps[key]
        yield from shape_records(ArmStepShape(*key), step.in_, step.out)


def plan_types(
    types: Mapping[TypeId, TypeSpec],
    inferences: Mapping[InferenceId, InferenceSpec] = NO_INFERENCES,
    tools: Mapping[ToolId, ToolSpec] = NO_TOOLS,
    steps: Mapping[StepKey, CodeNodeSpec] = NO_STEPS,
    arm_steps: Mapping[ArmStepKey, CodeNodeSpec] = NO_ARM_STEPS,
) -> GeneratedTypes:
    models = build_type_models(types)
    buildable = {type_id: spec for type_id, spec in types.items() if type_id in models.annotations}
    declared = declared_records(inferences, tools, steps, arm_steps)
    candidates = (record for record in declared if _buildable(models, record))
    taken = set(_defined_names(buildable))
    records: list[ShapeRecord] = []
    conflicts: list[ShapeRecord] = []
    for record in candidates:
        (conflicts if record.name in taken else records).append(record)
        taken.add(record.name)
    return GeneratedTypes(buildable, tuple(records), tuple(conflicts))


def render_types(
    types: Mapping[TypeId, TypeSpec],
    inferences: Mapping[InferenceId, InferenceSpec] = NO_INFERENCES,
    tools: Mapping[ToolId, ToolSpec] = NO_TOOLS,
    steps: Mapping[StepKey, CodeNodeSpec] = NO_STEPS,
    arm_steps: Mapping[ArmStepKey, CodeNodeSpec] = NO_ARM_STEPS,
) -> str:
    return render_plan(plan_types(types, inferences, tools, steps, arm_steps))


def render_plan(plan: GeneratedTypes) -> str:
    writer = _Writer(plan.types)
    blocks = [
        *(writer.definition(type_id, plan.types[type_id]) for type_id in _ordered(plan.types)),
        *(writer.record(record.name, None, record.fields) for record in plan.records),
    ]
    if not blocks:
        return ""
    after_imports = BLOCK_SEPARATOR if blocks[0].startswith(CLASS_PREFIX) else IMPORT_SEPARATOR
    return f"{GENERATED_HEADER}\n{writer.header()}{after_imports}{BLOCK_SEPARATOR.join(blocks)}\n"


def generate_types(root: Path) -> LoadResult:
    loaded = load_project(root)
    if loaded.project is None:
        return loaded
    target = root / GENERATED_TYPES
    text = render_plan(project_plan(loaded.project))
    current = target.read_text(encoding="utf-8") if target.is_file() else ""
    if current == text:
        return loaded
    if not text:
        target.unlink(missing_ok=True)
        return loaded
    target.write_text(text, encoding="utf-8")
    return loaded


@dataclass(slots=True)
class _Writer:
    types: Mapping[TypeId, TypeSpec]
    imports: dict[str, set[str]] = field(default_factory=dict[str, set[str]])

    def definition(self, type_id: TypeId, spec: TypeSpec) -> str:
        match spec:
            case RecordType():
                return self.record(type_id, None, spec.fields)
            case EnumType():
                return f"type {type_id} = {self.literal([value.value for value in spec.values])}"
            case UnionType():
                return self.union(type_id, spec)
            case IdType():
                return self.identifier(type_id, spec)
            case ValueType():
                return f"type {type_id} = {self.item(TypeId(spec.base), spec)}"
            case _:
                assert_never(spec)

    def header(self) -> str:
        lines = (
            "\n".join(self.import_line(module) for module in group if module in self.imports) for group in IMPORT_GROUPS
        )
        return "\n\n".join(line for line in lines if line)

    def import_line(self, module: str) -> str:
        return f"from {module} import {', '.join(sorted(self.imports[module], key=_import_order))}"

    def use(self, module: str, name: str) -> str:
        if module:
            self.imports.setdefault(module, set()).add(name)
        return name

    def record(self, name: str, tag: tuple[str, str] | None, fields: Sequence[FieldDecl]) -> str:
        members = [*((tag,) if tag is not None else ()), *((decl.name, self.annotation(decl)) for decl in fields)]
        lines = [
            f"class {name}({self.use('pydantic', 'BaseModel')}):",
            f"    model_config = {self.use('aqven.spec', 'GENERATED_CONFIG')}",
            *(f"    {self.attribute(member, annotation)}" for member, annotation in members),
        ]
        return "\n".join(lines)

    def attribute(self, name: str, annotation: str) -> str:
        if name not in RESERVED_NAMES:
            return f"{name}: {annotation}"
        return f"{name}_: {annotation} = {self.use('pydantic', 'Field')}(alias={_literal(name)})"

    def union(self, type_id: TypeId, spec: UnionType) -> str:
        names = [f"{type_id}{_pascal(variant.name)}" for variant in spec.variants]
        classes = [
            self.record(name, (spec.discriminator, self.literal([variant.name])), variant.fields)
            for name, variant in zip(names, spec.variants, strict=True)
        ]
        members = " | ".join(names)
        discriminated = self.constrained(members, "Field", f"discriminator={_literal(spec.discriminator)}")
        alias = members if len(names) == 1 else discriminated
        return BLOCK_SEPARATOR.join((*classes, f"type {type_id} = {alias}"))

    def identifier(self, type_id: TypeId, spec: IdType) -> str:
        new_type = f"{type_id} = {self.use('typing', 'NewType')}({_literal(type_id)}, str)"
        arguments = _arguments(("max_length", spec.max_length), ("pattern", spec.pattern))
        constrained = self.constrained(type_id, "StringConstraints", arguments)
        return f"{new_type}\n\ntype {type_id}{ID_FIELD_SUFFIX} = {constrained}"

    def annotation(self, decl: FieldDecl) -> str:
        ref = parse_type_ref(decl.type)
        item = self.item(ref.type_id, decl)
        listed = f"list[{item}]" if ref.is_list else item
        arguments = _arguments(("max_length", decl.max_items)) if ref.is_list else ""
        bounded = self.constrained(listed, "Field", arguments)
        return f"{bounded} | None" if ref.is_optional else bounded

    def item(self, type_id: TypeId, constraints: Constraints) -> str:
        writer = ITEM_WRITERS.get(type_id)
        if writer is not None:
            return writer(self, constraints)
        builtin = BUILTIN_NAMES.get(type_id)
        if builtin is not None:
            return self.use(*builtin)
        return f"{type_id}{ID_FIELD_SUFFIX}" if isinstance(self.types.get(type_id), IdType) else type_id

    def text(self, constraints: Constraints) -> str:
        if constraints.enum is not None:
            return self.literal(constraints.enum)
        arguments = _arguments(("max_length", constraints.max_length), ("pattern", constraints.pattern))
        return self.constrained("str", "StringConstraints", arguments)

    def integer(self, constraints: Constraints) -> str:
        return self.constrained("int", "Field", _bounds(constraints))

    def number(self, constraints: Constraints) -> str:
        return self.constrained("float", "Field", _bounds(constraints))

    def literal(self, values: Sequence[str]) -> str:
        return f"{self.use('typing', 'Literal')}[{', '.join(_literal(value) for value in values)}]"

    def constrained(self, base: str, factory: str, arguments: str) -> str:
        if not arguments:
            return base
        return f"{self.use('typing', 'Annotated')}[{base}, {self.use('pydantic', factory)}({arguments})]"


ITEM_WRITERS: Final[Mapping[TypeId, Callable[[_Writer, Constraints], str]]] = {
    TEXT: _Writer.text,
    INT: _Writer.integer,
    FLOAT: _Writer.number,
}


def _code_steps(flow: LoadedFlow) -> Iterator[tuple[NodeId, CodeNodeSpec]]:
    nodes = flow.nodes.items() if flow.builder_path is None else ()
    return ((node_id, spec) for node_id, source in nodes if isinstance(spec := source.spec, CodeNodeSpec))


def _buildable(models: TypeModels, record: ShapeRecord) -> bool:
    try:
        models.record(record.name, record.fields)
    except TypeModelError:
        return False
    return True


def _defined_names(types: Mapping[TypeId, TypeSpec]) -> Iterator[str]:
    for type_id, spec in types.items():
        yield type_id
        yield from (f"{type_id}{_pascal(variant.name)}" for variant in _variants(spec))
        yield from (f"{type_id}{ID_FIELD_SUFFIX}",) if isinstance(spec, IdType) else ()


def _ordered(types: Mapping[TypeId, TypeSpec]) -> tuple[TypeId, ...]:
    ordered: dict[TypeId, None] = {}
    for type_id in sorted(types):
        _visit(type_id, types, ordered)
    return tuple(ordered)


def _visit(type_id: TypeId, types: Mapping[TypeId, TypeSpec], ordered: dict[TypeId, None]) -> None:
    spec = types.get(type_id)
    if spec is None or type_id in ordered:
        return
    for dependency in sorted(_dependencies(spec)):
        _visit(dependency, types, ordered)
    ordered[type_id] = None


def _dependencies(spec: TypeSpec) -> frozenset[TypeId]:
    fields = [*_record_fields(spec), *(decl for variant in _variants(spec) for decl in variant.fields)]
    return frozenset(parse_type_ref(decl.type).type_id for decl in fields)


def _record_fields(spec: TypeSpec) -> Sequence[FieldDecl]:
    return spec.fields if isinstance(spec, RecordType) else ()


def _variants(spec: TypeSpec) -> Sequence[UnionVariant]:
    return spec.variants if isinstance(spec, UnionType) else ()


def _bounds(constraints: Constraints) -> str:
    return _arguments(("ge", constraints.minimum), ("le", constraints.maximum))


def _arguments(*pairs: tuple[str, str | int | float | None]) -> str:
    return ", ".join(f"{key}={_literal(value)}" for key, value in pairs if value is not None)


def _literal(value: str | int | float) -> str:
    return json.dumps(value, ensure_ascii=False) if isinstance(value, str) else repr(value)


def _pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _import_order(name: str) -> tuple[int, str]:
    rank = 0 if name.isupper() else 1 if name[0].isupper() else 2
    return rank, name.lower()
