apiVersion: "aqven/v1"
kind: "Type"
type: "enum"
description: "Валюта денежной суммы"
values:
- value: "eur"
  description: "Евро"
- value: "usd"
  description: "Доллар США"
- value: "gbp"
  description: "Фунт стерлингов"
