from decimal import Decimal
from typing import Final

SERIES_WORKFLOW: Final = "aqven.series"
SERIES_ATTEMPT_WORKFLOW: Final = "aqven.series_attempt"
SERIES_QUEUE: Final = "aqven.series_attempts"
SERIES_EVENTS_STREAM: Final = "series_events"
APPROVAL_TOPIC: Final = "series_approval"
ATTEMPT_SLOTS: Final = 4
LOOKAHEAD: Final = 8
QUEUE_POLL_SECONDS: Final = 0.25
APPROVAL_RECV_SECONDS: Final = 3600
MAX_WAIT_SECONDS: Final = 50
WAIT_POLL_SECONDS: Final = 1.0
CAP_HEADROOM: Final = Decimal("1.25")
INFRA_ERROR_LIMIT: Final = 0.05
MAX_ATTEMPTS: Final = 5000
MAX_LOOK_CASES: Final = 500
UNSTARTED_GRACE_SECONDS: Final = 60
