# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate.
from typing import Annotated, Literal

from pydantic import BaseModel, StringConstraints

from aqven.spec import GENERATED_CONFIG, Image


class Customer(BaseModel):
    model_config = GENERATED_CONFIG
    name: Annotated[str, StringConstraints(max_length=120)]
    email: Annotated[str, StringConstraints(max_length=254)] | None


type TriageCategory = Literal["billing", "delivery"]


class TriageResult(BaseModel):
    model_config = GENERATED_CONFIG
    category: TriageCategory
    summary: Annotated[str, StringConstraints(max_length=200)]


class TriageReview(BaseModel):
    model_config = GENERATED_CONFIG
    category: TriageCategory


class TriageTicket(BaseModel):
    model_config = GENERATED_CONFIG
    subject: Annotated[str, StringConstraints(max_length=200)]
    body: Annotated[str, StringConstraints(max_length=2000)]
    customer: Customer
    photo: Image | None


class ClassifyIn(BaseModel):
    model_config = GENERATED_CONFIG
    ticket: TriageTicket


class ClassifyOut(BaseModel):
    model_config = GENERATED_CONFIG
    rationale: Annotated[str, StringConstraints(max_length=300)]
    category: TriageCategory


class TriageSummarizeIn(BaseModel):
    model_config = GENERATED_CONFIG
    ticket: TriageTicket
    category: TriageCategory


class TriageSummarizeOut(BaseModel):
    model_config = GENERATED_CONFIG
    summary: Annotated[str, StringConstraints(max_length=200)]
