apiVersion: "aqven/v1"
kind: "Type"
type: "enum"
description: "Основной симптом дефекта товара"
values:
- value: "no_power"
  description: "Не включается"
- value: "flicker"
  description: "Мерцает"
- value: "dead_segment"
  description: "Не светится участок ленты"
- value: "overheating"
  description: "Перегревается"
- value: "app_offline"
  description: "Не подключается к приложению"
- value: "physical_damage"
  description: "Механическое повреждение корпуса или плафона"
