# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate.
from typing import Annotated, Literal

from pydantic import BaseModel, StringConstraints

from aqven.spec import GENERATED_CONFIG

type Mood = Literal["calm", "warm"]


class Note(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class ReplyIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class ReplyOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]
    mood: Mood


class StampIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class StampOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeCleanIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeCleanOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]
