# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate.
from typing import Annotated, Literal

from pydantic import BaseModel, Field, StringConstraints

from aqven.spec import GENERATED_CONFIG

type Mood = Literal["calm", "warm"]


class Note(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


type Score = Annotated[float, Field(ge=0, le=1)]


class LookupIn(BaseModel):
    model_config = GENERATED_CONFIG
    question: Annotated[str, StringConstraints(max_length=200)]


class LookupOut(BaseModel):
    model_config = GENERATED_CONFIG
    similar: Annotated[list[Note], Field(max_length=3)]
    score: Score


class RedoIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class RedoOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]
    score: Score


class ReplyIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]
    mood: Mood


class ReplyOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]
    mood: Mood
    score: Score


class StampIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class StampOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeCleanIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeCleanOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeTrimIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeTrimOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]
