from collections.abc import Iterator, Mapping, Sequence
from datetime import UTC
from typing import Final

from aqven.series.findings.layout import FINDING_GLOB, finding_file
from aqven.spec import FindingSpec, VerdictState
from aqven.write.canonical import document_bytes

FINDINGS_TITLE: Final = "# Findings"
FINDINGS_NOTE: Final = (
    f"Generated by aqven from {FINDING_GLOB}. Do not edit this file: run a new series on holdout cases instead."
)
OTHER_FAILURE_MODE: Final = "other"
SENTENCE_END: Final = "."
NO_MODEL: Final = "no model recorded"
SHELVES: Final[tuple[tuple[str, frozenset[VerdictState]], ...]] = (
    ("On holdout cases", frozenset({VerdictState.CONFIRMED, VerdictState.REFUTED})),
    ("Inconclusive", frozenset({VerdictState.INCONCLUSIVE})),
    ("Signals", frozenset({VerdictState.SIGNAL})),
)


def finding_bytes(spec: FindingSpec) -> bytes:
    return document_bytes(spec.model_dump(mode="json", by_alias=True))


def render_findings_md(findings: Sequence[FindingSpec], paths: Mapping[str, str]) -> str:
    ordered = sorted(findings, key=_order)
    if not ordered:
        return ""
    modes = tuple(dict.fromkeys(_failure_mode(finding) for finding in ordered))
    sections = (_mode_section(mode, ordered, paths) for mode in modes)
    return "\n\n".join((FINDINGS_TITLE, FINDINGS_NOTE, *sections)) + "\n"


def _failure_mode(finding: FindingSpec) -> str:
    return finding.failure_mode or OTHER_FAILURE_MODE


def _order(finding: FindingSpec) -> tuple[str, str, str, str]:
    return (_failure_mode(finding), finding.experiment, finding.scope.finished_at.isoformat(), finding.series)


def _mode_section(mode: str, ordered: Sequence[FindingSpec], paths: Mapping[str, str]) -> str:
    members = tuple(finding for finding in ordered if _failure_mode(finding) == mode)
    shelves = tuple(_shelf(title, states, members, ordered, paths) for title, states in SHELVES)
    return "\n\n".join((f"## {mode}", *(shelf for shelf in shelves if shelf)))


def _shelf(
    title: str,
    states: frozenset[VerdictState],
    members: Sequence[FindingSpec],
    everything: Sequence[FindingSpec],
    paths: Mapping[str, str],
) -> str:
    bullets = tuple(_bullet(finding, everything, paths) for finding in members if finding.state in states)
    if not bullets:
        return ""
    return "\n\n".join((f"### {title}", "\n".join(bullets)))


def _bullet(finding: FindingSpec, everything: Sequence[FindingSpec], paths: Mapping[str, str]) -> str:
    path = paths.get(finding.series) or finding_file(finding.experiment, finding.series)
    parts = (
        f"- **{finding.state.value}** `{finding.experiment}`: {_sentence(finding.statement)}",
        f"Scope: {_scope(finding)}.",
        *_looks(finding, everything),
        f"[finding]({path})",
    )
    return " ".join(parts)


def _sentence(text: str) -> str:
    stripped = text.strip()
    return stripped if stripped.endswith(SENTENCE_END) else f"{stripped}{SENTENCE_END}"


def _scope(finding: FindingSpec) -> str:
    scope = finding.scope
    models = sorted({model for variant in finding.variants for model in variant.models})
    day = scope.finished_at.astimezone(UTC).date().isoformat()
    return f"{scope.split}, {scope.cases} × {scope.repeats}, {', '.join(models) or NO_MODEL}, {day}"


def _looks(finding: FindingSpec, everything: Sequence[FindingSpec]) -> Iterator[str]:
    peers = tuple(
        other
        for other in everything
        if other.experiment == finding.experiment and other.scope.case_names_sha256 == finding.scope.case_names_sha256
    )
    if len(peers) < 2:
        return
    confirmed = sum(1 for other in peers if other.state is VerdictState.CONFIRMED)
    yield f"Confirmed in {confirmed} of {len(peers)} holdout looks."
