apiVersion: "aqven/v1"
kind: "Type"
type: "enum"
description: "Действие по обращению"
values:
- value: "store_credit"
  description: "Начислить кредит магазина"
- value: "replacement"
  description: "Заменить товар"
- value: "reship"
  description: "Отправить заказ повторно"
- value: "advice"
  description: "Дать совет без компенсации"
