# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate.
from typing import Annotated

from pydantic import BaseModel, StringConstraints

from aqven.spec import GENERATED_CONFIG


class Note(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class ReplyIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class ReplyOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class StampIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class StampOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class AuditSealIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class AuditSealOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeCleanIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeCleanOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeFinishIn(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]


class IntakeFinishOut(BaseModel):
    model_config = GENERATED_CONFIG
    text: Annotated[str, StringConstraints(max_length=200)]
