# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate.
from typing import Literal

from pydantic import BaseModel

from aqven.spec import GENERATED_CONFIG

type Priority = Literal["low", "high"]


class Ticket(BaseModel):
    model_config = GENERATED_CONFIG
    text: str
    priority: Priority


class Reply(BaseModel):
    model_config = GENERATED_CONFIG
    text: str


class Stamped(BaseModel):
    model_config = GENERATED_CONFIG
    text: str
    key: str | None
    blob_id: str
    token_tail: str
