/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as FlowsFlowIdRouteRouteImport } from './routes/flows/$flowId/route'
import { Route as FlowsFlowIdIndexRouteImport } from './routes/flows/$flowId/index'
import { Route as FlowsFlowIdCanvasRouteImport } from './routes/flows/$flowId/canvas'
import { Route as FlowsFlowIdDatasetsRouteImport } from './routes/flows/$flowId/datasets'
import { Route as FlowsFlowIdNodesRouteImport } from './routes/flows/$flowId/nodes'
import { Route as FlowsFlowIdReviewRouteImport } from './routes/flows/$flowId/review'
import { Route as FlowsFlowIdRunsRouteImport } from './routes/flows/$flowId/runs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRouteRoute = FlowsFlowIdRouteRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdIndexRoute = FlowsFlowIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlowsFlowIdRouteRoute,
} as any)
const FlowsFlowIdCanvasRoute = FlowsFlowIdCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => FlowsFlowIdRouteRoute,
} as any)
const FlowsFlowIdDatasetsRoute = FlowsFlowIdDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => FlowsFlowIdRouteRoute,
} as any)
const FlowsFlowIdNodesRoute = FlowsFlowIdNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => FlowsFlowIdRouteRoute,
} as any)
const FlowsFlowIdReviewRoute = FlowsFlowIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => FlowsFlowIdRouteRoute,
} as any)
const FlowsFlowIdRunsRoute = FlowsFlowIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => FlowsFlowIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/flows/$flowId': typeof FlowsFlowIdRouteRouteWithChildren
  '/flows/$flowId/canvas': typeof FlowsFlowIdCanvasRoute
  '/flows/$flowId/datasets': typeof FlowsFlowIdDatasetsRoute
  '/flows/$flowId/nodes': typeof FlowsFlowIdNodesRoute
  '/flows/$flowId/review': typeof FlowsFlowIdReviewRoute
  '/flows/$flowId/runs': typeof FlowsFlowIdRunsRoute
  '/flows/$flowId/': typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/flows/$flowId/canvas': typeof FlowsFlowIdCanvasRoute
  '/flows/$flowId/datasets': typeof FlowsFlowIdDatasetsRoute
  '/flows/$flowId/nodes': typeof FlowsFlowIdNodesRoute
  '/flows/$flowId/review': typeof FlowsFlowIdReviewRoute
  '/flows/$flowId/runs': typeof FlowsFlowIdRunsRoute
  '/flows/$flowId': typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/flows/$flowId': typeof FlowsFlowIdRouteRouteWithChildren
  '/flows/$flowId/canvas': typeof FlowsFlowIdCanvasRoute
  '/flows/$flowId/datasets': typeof FlowsFlowIdDatasetsRoute
  '/flows/$flowId/nodes': typeof FlowsFlowIdNodesRoute
  '/flows/$flowId/review': typeof FlowsFlowIdReviewRoute
  '/flows/$flowId/runs': typeof FlowsFlowIdRunsRoute
  '/flows/$flowId/': typeof FlowsFlowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/settings'
    | '/setup'
    | '/flows/$flowId'
    | '/flows/$flowId/canvas'
    | '/flows/$flowId/datasets'
    | '/flows/$flowId/nodes'
    | '/flows/$flowId/review'
    | '/flows/$flowId/runs'
    | '/flows/$flowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/settings'
    | '/setup'
    | '/flows/$flowId/canvas'
    | '/flows/$flowId/datasets'
    | '/flows/$flowId/nodes'
    | '/flows/$flowId/review'
    | '/flows/$flowId/runs'
    | '/flows/$flowId'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/settings'
    | '/setup'
    | '/flows/$flowId'
    | '/flows/$flowId/canvas'
    | '/flows/$flowId/datasets'
    | '/flows/$flowId/nodes'
    | '/flows/$flowId/review'
    | '/flows/$flowId/runs'
    | '/flows/$flowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  FlowsFlowIdRouteRoute: typeof FlowsFlowIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/': {
      id: '/flows/$flowId/'
      path: '/'
      fullPath: '/flows/$flowId/'
      preLoaderRoute: typeof FlowsFlowIdIndexRouteImport
      parentRoute: typeof FlowsFlowIdRouteRoute
    }
    '/flows/$flowId/canvas': {
      id: '/flows/$flowId/canvas'
      path: '/canvas'
      fullPath: '/flows/$flowId/canvas'
      preLoaderRoute: typeof FlowsFlowIdCanvasRouteImport
      parentRoute: typeof FlowsFlowIdRouteRoute
    }
    '/flows/$flowId/datasets': {
      id: '/flows/$flowId/datasets'
      path: '/datasets'
      fullPath: '/flows/$flowId/datasets'
      preLoaderRoute: typeof FlowsFlowIdDatasetsRouteImport
      parentRoute: typeof FlowsFlowIdRouteRoute
    }
    '/flows/$flowId/nodes': {
      id: '/flows/$flowId/nodes'
      path: '/nodes'
      fullPath: '/flows/$flowId/nodes'
      preLoaderRoute: typeof FlowsFlowIdNodesRouteImport
      parentRoute: typeof FlowsFlowIdRouteRoute
    }
    '/flows/$flowId/review': {
      id: '/flows/$flowId/review'
      path: '/review'
      fullPath: '/flows/$flowId/review'
      preLoaderRoute: typeof FlowsFlowIdReviewRouteImport
      parentRoute: typeof FlowsFlowIdRouteRoute
    }
    '/flows/$flowId/runs': {
      id: '/flows/$flowId/runs'
      path: '/runs'
      fullPath: '/flows/$flowId/runs'
      preLoaderRoute: typeof FlowsFlowIdRunsRouteImport
      parentRoute: typeof FlowsFlowIdRouteRoute
    }
  }
}

interface FlowsFlowIdRouteRouteChildren {
  FlowsFlowIdCanvasRoute: typeof FlowsFlowIdCanvasRoute
  FlowsFlowIdDatasetsRoute: typeof FlowsFlowIdDatasetsRoute
  FlowsFlowIdNodesRoute: typeof FlowsFlowIdNodesRoute
  FlowsFlowIdReviewRoute: typeof FlowsFlowIdReviewRoute
  FlowsFlowIdRunsRoute: typeof FlowsFlowIdRunsRoute
  FlowsFlowIdIndexRoute: typeof FlowsFlowIdIndexRoute
}

const FlowsFlowIdRouteRouteChildren: FlowsFlowIdRouteRouteChildren = {
  FlowsFlowIdCanvasRoute: FlowsFlowIdCanvasRoute,
  FlowsFlowIdDatasetsRoute: FlowsFlowIdDatasetsRoute,
  FlowsFlowIdNodesRoute: FlowsFlowIdNodesRoute,
  FlowsFlowIdReviewRoute: FlowsFlowIdReviewRoute,
  FlowsFlowIdRunsRoute: FlowsFlowIdRunsRoute,
  FlowsFlowIdIndexRoute: FlowsFlowIdIndexRoute,
}

const FlowsFlowIdRouteRouteWithChildren =
  FlowsFlowIdRouteRoute._addFileChildren(FlowsFlowIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  FlowsFlowIdRouteRoute: FlowsFlowIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
