/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteRouteImport } from './routes/_project/route'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProjectIndexRouteImport } from './routes/_project/index'
import { Route as ProjectSettingsRouteImport } from './routes/_project/settings'
import { Route as ProjectFlowsFlowIdRouteRouteImport } from './routes/_project/flows/$flowId/route'
import { Route as ProjectResearchIndexRouteImport } from './routes/_project/research/index'
import { Route as ProjectRunsRunIdRouteImport } from './routes/_project/runs/$runId'
import { Route as ProjectFlowsFlowIdIndexRouteImport } from './routes/_project/flows/$flowId/index'
import { Route as ProjectFlowsFlowIdCanvasRouteImport } from './routes/_project/flows/$flowId/canvas'
import { Route as ProjectFlowsFlowIdCasesRouteImport } from './routes/_project/flows/$flowId/cases'
import { Route as ProjectFlowsFlowIdRunsRouteImport } from './routes/_project/flows/$flowId/runs'
import { Route as ProjectResearchExperimentsExperimentIdRouteImport } from './routes/_project/research/experiments/$experimentId'
import { Route as ProjectResearchExperimentsNewRouteImport } from './routes/_project/research/experiments/new'
import { Route as ProjectResearchSeriesIndexRouteImport } from './routes/_project/research/series/index'
import { Route as ProjectResearchSeriesSeriesIdRouteImport } from './routes/_project/research/series/$seriesId'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectSettingsRoute = ProjectSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectFlowsFlowIdRouteRoute = ProjectFlowsFlowIdRouteRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectResearchIndexRoute = ProjectResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectRunsRunIdRoute = ProjectRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectFlowsFlowIdIndexRoute = ProjectFlowsFlowIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectFlowsFlowIdRouteRoute,
} as any)
const ProjectFlowsFlowIdCanvasRoute =
  ProjectFlowsFlowIdCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => ProjectFlowsFlowIdRouteRoute,
  } as any)
const ProjectFlowsFlowIdCasesRoute = ProjectFlowsFlowIdCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => ProjectFlowsFlowIdRouteRoute,
} as any)
const ProjectFlowsFlowIdRunsRoute = ProjectFlowsFlowIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ProjectFlowsFlowIdRouteRoute,
} as any)
const ProjectResearchExperimentsExperimentIdRoute =
  ProjectResearchExperimentsExperimentIdRouteImport.update({
    id: '/research/experiments/$experimentId',
    path: '/research/experiments/$experimentId',
    getParentRoute: () => ProjectRouteRoute,
  } as any)
const ProjectResearchExperimentsNewRoute =
  ProjectResearchExperimentsNewRouteImport.update({
    id: '/research/experiments/new',
    path: '/research/experiments/new',
    getParentRoute: () => ProjectRouteRoute,
  } as any)
const ProjectResearchSeriesIndexRoute =
  ProjectResearchSeriesIndexRouteImport.update({
    id: '/research/series/',
    path: '/research/series/',
    getParentRoute: () => ProjectRouteRoute,
  } as any)
const ProjectResearchSeriesSeriesIdRoute =
  ProjectResearchSeriesSeriesIdRouteImport.update({
    id: '/research/series/$seriesId',
    path: '/research/series/$seriesId',
    getParentRoute: () => ProjectRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProjectIndexRoute
  '/demo': typeof DemoRoute
  '/setup': typeof SetupRoute
  '/settings': typeof ProjectSettingsRoute
  '/flows/$flowId': typeof ProjectFlowsFlowIdRouteRouteWithChildren
  '/runs/$runId': typeof ProjectRunsRunIdRoute
  '/research/': typeof ProjectResearchIndexRoute
  '/flows/$flowId/canvas': typeof ProjectFlowsFlowIdCanvasRoute
  '/flows/$flowId/cases': typeof ProjectFlowsFlowIdCasesRoute
  '/flows/$flowId/runs': typeof ProjectFlowsFlowIdRunsRoute
  '/research/experiments/$experimentId': typeof ProjectResearchExperimentsExperimentIdRoute
  '/research/experiments/new': typeof ProjectResearchExperimentsNewRoute
  '/research/series/$seriesId': typeof ProjectResearchSeriesSeriesIdRoute
  '/flows/$flowId/': typeof ProjectFlowsFlowIdIndexRoute
  '/research/series/': typeof ProjectResearchSeriesIndexRoute
}
export interface FileRoutesByTo {
  '/demo': typeof DemoRoute
  '/setup': typeof SetupRoute
  '/settings': typeof ProjectSettingsRoute
  '/': typeof ProjectIndexRoute
  '/runs/$runId': typeof ProjectRunsRunIdRoute
  '/research': typeof ProjectResearchIndexRoute
  '/flows/$flowId/canvas': typeof ProjectFlowsFlowIdCanvasRoute
  '/flows/$flowId/cases': typeof ProjectFlowsFlowIdCasesRoute
  '/flows/$flowId/runs': typeof ProjectFlowsFlowIdRunsRoute
  '/research/experiments/$experimentId': typeof ProjectResearchExperimentsExperimentIdRoute
  '/research/experiments/new': typeof ProjectResearchExperimentsNewRoute
  '/research/series/$seriesId': typeof ProjectResearchSeriesSeriesIdRoute
  '/flows/$flowId': typeof ProjectFlowsFlowIdIndexRoute
  '/research/series': typeof ProjectResearchSeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_project': typeof ProjectRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/setup': typeof SetupRoute
  '/_project/settings': typeof ProjectSettingsRoute
  '/_project/': typeof ProjectIndexRoute
  '/_project/flows/$flowId': typeof ProjectFlowsFlowIdRouteRouteWithChildren
  '/_project/runs/$runId': typeof ProjectRunsRunIdRoute
  '/_project/research/': typeof ProjectResearchIndexRoute
  '/_project/flows/$flowId/canvas': typeof ProjectFlowsFlowIdCanvasRoute
  '/_project/flows/$flowId/cases': typeof ProjectFlowsFlowIdCasesRoute
  '/_project/flows/$flowId/runs': typeof ProjectFlowsFlowIdRunsRoute
  '/_project/research/experiments/$experimentId': typeof ProjectResearchExperimentsExperimentIdRoute
  '/_project/research/experiments/new': typeof ProjectResearchExperimentsNewRoute
  '/_project/research/series/$seriesId': typeof ProjectResearchSeriesSeriesIdRoute
  '/_project/flows/$flowId/': typeof ProjectFlowsFlowIdIndexRoute
  '/_project/research/series/': typeof ProjectResearchSeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/setup'
    | '/settings'
    | '/flows/$flowId'
    | '/runs/$runId'
    | '/research/'
    | '/flows/$flowId/canvas'
    | '/flows/$flowId/cases'
    | '/flows/$flowId/runs'
    | '/research/experiments/$experimentId'
    | '/research/experiments/new'
    | '/research/series/$seriesId'
    | '/flows/$flowId/'
    | '/research/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demo'
    | '/setup'
    | '/settings'
    | '/'
    | '/runs/$runId'
    | '/research'
    | '/flows/$flowId/canvas'
    | '/flows/$flowId/cases'
    | '/flows/$flowId/runs'
    | '/research/experiments/$experimentId'
    | '/research/experiments/new'
    | '/research/series/$seriesId'
    | '/flows/$flowId'
    | '/research/series'
  id:
    | '__root__'
    | '/_project'
    | '/demo'
    | '/setup'
    | '/_project/settings'
    | '/_project/'
    | '/_project/flows/$flowId'
    | '/_project/runs/$runId'
    | '/_project/research/'
    | '/_project/flows/$flowId/canvas'
    | '/_project/flows/$flowId/cases'
    | '/_project/flows/$flowId/runs'
    | '/_project/research/experiments/$experimentId'
    | '/_project/research/experiments/new'
    | '/_project/research/series/$seriesId'
    | '/_project/flows/$flowId/'
    | '/_project/research/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project/': {
      id: '/_project/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/settings': {
      id: '/_project/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProjectSettingsRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/flows/$flowId': {
      id: '/_project/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof ProjectFlowsFlowIdRouteRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/research/': {
      id: '/_project/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ProjectResearchIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/runs/$runId': {
      id: '/_project/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof ProjectRunsRunIdRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/flows/$flowId/': {
      id: '/_project/flows/$flowId/'
      path: '/'
      fullPath: '/flows/$flowId/'
      preLoaderRoute: typeof ProjectFlowsFlowIdIndexRouteImport
      parentRoute: typeof ProjectFlowsFlowIdRouteRoute
    }
    '/_project/flows/$flowId/canvas': {
      id: '/_project/flows/$flowId/canvas'
      path: '/canvas'
      fullPath: '/flows/$flowId/canvas'
      preLoaderRoute: typeof ProjectFlowsFlowIdCanvasRouteImport
      parentRoute: typeof ProjectFlowsFlowIdRouteRoute
    }
    '/_project/flows/$flowId/cases': {
      id: '/_project/flows/$flowId/cases'
      path: '/cases'
      fullPath: '/flows/$flowId/cases'
      preLoaderRoute: typeof ProjectFlowsFlowIdCasesRouteImport
      parentRoute: typeof ProjectFlowsFlowIdRouteRoute
    }
    '/_project/flows/$flowId/runs': {
      id: '/_project/flows/$flowId/runs'
      path: '/runs'
      fullPath: '/flows/$flowId/runs'
      preLoaderRoute: typeof ProjectFlowsFlowIdRunsRouteImport
      parentRoute: typeof ProjectFlowsFlowIdRouteRoute
    }
    '/_project/research/experiments/$experimentId': {
      id: '/_project/research/experiments/$experimentId'
      path: '/research/experiments/$experimentId'
      fullPath: '/research/experiments/$experimentId'
      preLoaderRoute: typeof ProjectResearchExperimentsExperimentIdRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/research/experiments/new': {
      id: '/_project/research/experiments/new'
      path: '/research/experiments/new'
      fullPath: '/research/experiments/new'
      preLoaderRoute: typeof ProjectResearchExperimentsNewRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/research/series/': {
      id: '/_project/research/series/'
      path: '/research/series'
      fullPath: '/research/series/'
      preLoaderRoute: typeof ProjectResearchSeriesIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/_project/research/series/$seriesId': {
      id: '/_project/research/series/$seriesId'
      path: '/research/series/$seriesId'
      fullPath: '/research/series/$seriesId'
      preLoaderRoute: typeof ProjectResearchSeriesSeriesIdRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
  }
}

interface ProjectFlowsFlowIdRouteRouteChildren {
  ProjectFlowsFlowIdCanvasRoute: typeof ProjectFlowsFlowIdCanvasRoute
  ProjectFlowsFlowIdCasesRoute: typeof ProjectFlowsFlowIdCasesRoute
  ProjectFlowsFlowIdRunsRoute: typeof ProjectFlowsFlowIdRunsRoute
  ProjectFlowsFlowIdIndexRoute: typeof ProjectFlowsFlowIdIndexRoute
}

const ProjectFlowsFlowIdRouteRouteChildren: ProjectFlowsFlowIdRouteRouteChildren =
  {
    ProjectFlowsFlowIdCanvasRoute: ProjectFlowsFlowIdCanvasRoute,
    ProjectFlowsFlowIdCasesRoute: ProjectFlowsFlowIdCasesRoute,
    ProjectFlowsFlowIdRunsRoute: ProjectFlowsFlowIdRunsRoute,
    ProjectFlowsFlowIdIndexRoute: ProjectFlowsFlowIdIndexRoute,
  }

const ProjectFlowsFlowIdRouteRouteWithChildren =
  ProjectFlowsFlowIdRouteRoute._addFileChildren(
    ProjectFlowsFlowIdRouteRouteChildren,
  )

interface ProjectRouteRouteChildren {
  ProjectSettingsRoute: typeof ProjectSettingsRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  ProjectFlowsFlowIdRouteRoute: typeof ProjectFlowsFlowIdRouteRouteWithChildren
  ProjectRunsRunIdRoute: typeof ProjectRunsRunIdRoute
  ProjectResearchIndexRoute: typeof ProjectResearchIndexRoute
  ProjectResearchExperimentsExperimentIdRoute: typeof ProjectResearchExperimentsExperimentIdRoute
  ProjectResearchExperimentsNewRoute: typeof ProjectResearchExperimentsNewRoute
  ProjectResearchSeriesSeriesIdRoute: typeof ProjectResearchSeriesSeriesIdRoute
  ProjectResearchSeriesIndexRoute: typeof ProjectResearchSeriesIndexRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectSettingsRoute: ProjectSettingsRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectFlowsFlowIdRouteRoute: ProjectFlowsFlowIdRouteRouteWithChildren,
  ProjectRunsRunIdRoute: ProjectRunsRunIdRoute,
  ProjectResearchIndexRoute: ProjectResearchIndexRoute,
  ProjectResearchExperimentsExperimentIdRoute:
    ProjectResearchExperimentsExperimentIdRoute,
  ProjectResearchExperimentsNewRoute: ProjectResearchExperimentsNewRoute,
  ProjectResearchSeriesSeriesIdRoute: ProjectResearchSeriesSeriesIdRoute,
  ProjectResearchSeriesIndexRoute: ProjectResearchSeriesIndexRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
