/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleDemoRouteImport } from './routes/$locale/demo'
import { Route as LocaleSettingsRouteImport } from './routes/$locale/settings'
import { Route as LocaleSetupRouteImport } from './routes/$locale/setup'
import { Route as LocaleWorkspaceIdWorkflowIdRouteRouteImport } from './routes/$locale/$workspaceId/$workflowId/route'
import { Route as LocaleWorkspaceIdWorkflowIdIndexRouteImport } from './routes/$locale/$workspaceId/$workflowId/index'
import { Route as LocaleWorkspaceIdWorkflowIdDataflowRouteImport } from './routes/$locale/$workspaceId/$workflowId/dataflow'
import { Route as LocaleWorkspaceIdWorkflowIdNodesRouteImport } from './routes/$locale/$workspaceId/$workflowId/nodes'
import { Route as LocaleWorkspaceIdWorkflowIdReviewRouteImport } from './routes/$locale/$workspaceId/$workflowId/review'
import { Route as LocaleWorkspaceIdWorkflowIdSchemaRouteImport } from './routes/$locale/$workspaceId/$workflowId/schema'
import { Route as LocaleWorkspaceIdWorkflowIdTestsIndexRouteImport } from './routes/$locale/$workspaceId/$workflowId/tests/index'
import { Route as LocaleWorkspaceIdWorkflowIdTestsTestIdRouteImport } from './routes/$locale/$workspaceId/$workflowId/tests/$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDemoRoute = LocaleDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSettingsRoute = LocaleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSetupRoute = LocaleSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleWorkspaceIdWorkflowIdRouteRoute =
  LocaleWorkspaceIdWorkflowIdRouteRouteImport.update({
    id: '/$workspaceId/$workflowId',
    path: '/$workspaceId/$workflowId',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleWorkspaceIdWorkflowIdIndexRoute =
  LocaleWorkspaceIdWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleWorkspaceIdWorkflowIdRouteRoute,
  } as any)
const LocaleWorkspaceIdWorkflowIdDataflowRoute =
  LocaleWorkspaceIdWorkflowIdDataflowRouteImport.update({
    id: '/dataflow',
    path: '/dataflow',
    getParentRoute: () => LocaleWorkspaceIdWorkflowIdRouteRoute,
  } as any)
const LocaleWorkspaceIdWorkflowIdNodesRoute =
  LocaleWorkspaceIdWorkflowIdNodesRouteImport.update({
    id: '/nodes',
    path: '/nodes',
    getParentRoute: () => LocaleWorkspaceIdWorkflowIdRouteRoute,
  } as any)
const LocaleWorkspaceIdWorkflowIdReviewRoute =
  LocaleWorkspaceIdWorkflowIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => LocaleWorkspaceIdWorkflowIdRouteRoute,
  } as any)
const LocaleWorkspaceIdWorkflowIdSchemaRoute =
  LocaleWorkspaceIdWorkflowIdSchemaRouteImport.update({
    id: '/schema',
    path: '/schema',
    getParentRoute: () => LocaleWorkspaceIdWorkflowIdRouteRoute,
  } as any)
const LocaleWorkspaceIdWorkflowIdTestsIndexRoute =
  LocaleWorkspaceIdWorkflowIdTestsIndexRouteImport.update({
    id: '/tests/',
    path: '/tests/',
    getParentRoute: () => LocaleWorkspaceIdWorkflowIdRouteRoute,
  } as any)
const LocaleWorkspaceIdWorkflowIdTestsTestIdRoute =
  LocaleWorkspaceIdWorkflowIdTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => LocaleWorkspaceIdWorkflowIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/demo': typeof LocaleDemoRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$workspaceId/$workflowId': typeof LocaleWorkspaceIdWorkflowIdRouteRouteWithChildren
  '/$locale/$workspaceId/$workflowId/dataflow': typeof LocaleWorkspaceIdWorkflowIdDataflowRoute
  '/$locale/$workspaceId/$workflowId/nodes': typeof LocaleWorkspaceIdWorkflowIdNodesRoute
  '/$locale/$workspaceId/$workflowId/review': typeof LocaleWorkspaceIdWorkflowIdReviewRoute
  '/$locale/$workspaceId/$workflowId/schema': typeof LocaleWorkspaceIdWorkflowIdSchemaRoute
  '/$locale/$workspaceId/$workflowId/': typeof LocaleWorkspaceIdWorkflowIdIndexRoute
  '/$locale/$workspaceId/$workflowId/tests/$testId': typeof LocaleWorkspaceIdWorkflowIdTestsTestIdRoute
  '/$locale/$workspaceId/$workflowId/tests/': typeof LocaleWorkspaceIdWorkflowIdTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/demo': typeof LocaleDemoRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$workspaceId/$workflowId/dataflow': typeof LocaleWorkspaceIdWorkflowIdDataflowRoute
  '/$locale/$workspaceId/$workflowId/nodes': typeof LocaleWorkspaceIdWorkflowIdNodesRoute
  '/$locale/$workspaceId/$workflowId/review': typeof LocaleWorkspaceIdWorkflowIdReviewRoute
  '/$locale/$workspaceId/$workflowId/schema': typeof LocaleWorkspaceIdWorkflowIdSchemaRoute
  '/$locale/$workspaceId/$workflowId': typeof LocaleWorkspaceIdWorkflowIdIndexRoute
  '/$locale/$workspaceId/$workflowId/tests/$testId': typeof LocaleWorkspaceIdWorkflowIdTestsTestIdRoute
  '/$locale/$workspaceId/$workflowId/tests': typeof LocaleWorkspaceIdWorkflowIdTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/demo': typeof LocaleDemoRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$workspaceId/$workflowId': typeof LocaleWorkspaceIdWorkflowIdRouteRouteWithChildren
  '/$locale/$workspaceId/$workflowId/dataflow': typeof LocaleWorkspaceIdWorkflowIdDataflowRoute
  '/$locale/$workspaceId/$workflowId/nodes': typeof LocaleWorkspaceIdWorkflowIdNodesRoute
  '/$locale/$workspaceId/$workflowId/review': typeof LocaleWorkspaceIdWorkflowIdReviewRoute
  '/$locale/$workspaceId/$workflowId/schema': typeof LocaleWorkspaceIdWorkflowIdSchemaRoute
  '/$locale/$workspaceId/$workflowId/': typeof LocaleWorkspaceIdWorkflowIdIndexRoute
  '/$locale/$workspaceId/$workflowId/tests/$testId': typeof LocaleWorkspaceIdWorkflowIdTestsTestIdRoute
  '/$locale/$workspaceId/$workflowId/tests/': typeof LocaleWorkspaceIdWorkflowIdTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/demo'
    | '/$locale/settings'
    | '/$locale/setup'
    | '/$locale/'
    | '/$locale/$workspaceId/$workflowId'
    | '/$locale/$workspaceId/$workflowId/dataflow'
    | '/$locale/$workspaceId/$workflowId/nodes'
    | '/$locale/$workspaceId/$workflowId/review'
    | '/$locale/$workspaceId/$workflowId/schema'
    | '/$locale/$workspaceId/$workflowId/'
    | '/$locale/$workspaceId/$workflowId/tests/$testId'
    | '/$locale/$workspaceId/$workflowId/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/demo'
    | '/$locale/settings'
    | '/$locale/setup'
    | '/$locale'
    | '/$locale/$workspaceId/$workflowId/dataflow'
    | '/$locale/$workspaceId/$workflowId/nodes'
    | '/$locale/$workspaceId/$workflowId/review'
    | '/$locale/$workspaceId/$workflowId/schema'
    | '/$locale/$workspaceId/$workflowId'
    | '/$locale/$workspaceId/$workflowId/tests/$testId'
    | '/$locale/$workspaceId/$workflowId/tests'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/demo'
    | '/$locale/settings'
    | '/$locale/setup'
    | '/$locale/'
    | '/$locale/$workspaceId/$workflowId'
    | '/$locale/$workspaceId/$workflowId/dataflow'
    | '/$locale/$workspaceId/$workflowId/nodes'
    | '/$locale/$workspaceId/$workflowId/review'
    | '/$locale/$workspaceId/$workflowId/schema'
    | '/$locale/$workspaceId/$workflowId/'
    | '/$locale/$workspaceId/$workflowId/tests/$testId'
    | '/$locale/$workspaceId/$workflowId/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/demo': {
      id: '/$locale/demo'
      path: '/demo'
      fullPath: '/$locale/demo'
      preLoaderRoute: typeof LocaleDemoRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/settings': {
      id: '/$locale/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleSettingsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/setup': {
      id: '/$locale/setup'
      path: '/setup'
      fullPath: '/$locale/setup'
      preLoaderRoute: typeof LocaleSetupRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$workspaceId/$workflowId': {
      id: '/$locale/$workspaceId/$workflowId'
      path: '/$workspaceId/$workflowId'
      fullPath: '/$locale/$workspaceId/$workflowId'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$workspaceId/$workflowId/': {
      id: '/$locale/$workspaceId/$workflowId/'
      path: '/'
      fullPath: '/$locale/$workspaceId/$workflowId/'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdIndexRouteImport
      parentRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRoute
    }
    '/$locale/$workspaceId/$workflowId/dataflow': {
      id: '/$locale/$workspaceId/$workflowId/dataflow'
      path: '/dataflow'
      fullPath: '/$locale/$workspaceId/$workflowId/dataflow'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdDataflowRouteImport
      parentRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRoute
    }
    '/$locale/$workspaceId/$workflowId/nodes': {
      id: '/$locale/$workspaceId/$workflowId/nodes'
      path: '/nodes'
      fullPath: '/$locale/$workspaceId/$workflowId/nodes'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdNodesRouteImport
      parentRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRoute
    }
    '/$locale/$workspaceId/$workflowId/review': {
      id: '/$locale/$workspaceId/$workflowId/review'
      path: '/review'
      fullPath: '/$locale/$workspaceId/$workflowId/review'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdReviewRouteImport
      parentRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRoute
    }
    '/$locale/$workspaceId/$workflowId/schema': {
      id: '/$locale/$workspaceId/$workflowId/schema'
      path: '/schema'
      fullPath: '/$locale/$workspaceId/$workflowId/schema'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdSchemaRouteImport
      parentRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRoute
    }
    '/$locale/$workspaceId/$workflowId/tests/': {
      id: '/$locale/$workspaceId/$workflowId/tests/'
      path: '/tests'
      fullPath: '/$locale/$workspaceId/$workflowId/tests/'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdTestsIndexRouteImport
      parentRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRoute
    }
    '/$locale/$workspaceId/$workflowId/tests/$testId': {
      id: '/$locale/$workspaceId/$workflowId/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/$locale/$workspaceId/$workflowId/tests/$testId'
      preLoaderRoute: typeof LocaleWorkspaceIdWorkflowIdTestsTestIdRouteImport
      parentRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRoute
    }
  }
}

interface LocaleWorkspaceIdWorkflowIdRouteRouteChildren {
  LocaleWorkspaceIdWorkflowIdDataflowRoute: typeof LocaleWorkspaceIdWorkflowIdDataflowRoute
  LocaleWorkspaceIdWorkflowIdNodesRoute: typeof LocaleWorkspaceIdWorkflowIdNodesRoute
  LocaleWorkspaceIdWorkflowIdReviewRoute: typeof LocaleWorkspaceIdWorkflowIdReviewRoute
  LocaleWorkspaceIdWorkflowIdSchemaRoute: typeof LocaleWorkspaceIdWorkflowIdSchemaRoute
  LocaleWorkspaceIdWorkflowIdIndexRoute: typeof LocaleWorkspaceIdWorkflowIdIndexRoute
  LocaleWorkspaceIdWorkflowIdTestsTestIdRoute: typeof LocaleWorkspaceIdWorkflowIdTestsTestIdRoute
  LocaleWorkspaceIdWorkflowIdTestsIndexRoute: typeof LocaleWorkspaceIdWorkflowIdTestsIndexRoute
}

const LocaleWorkspaceIdWorkflowIdRouteRouteChildren: LocaleWorkspaceIdWorkflowIdRouteRouteChildren =
  {
    LocaleWorkspaceIdWorkflowIdDataflowRoute:
      LocaleWorkspaceIdWorkflowIdDataflowRoute,
    LocaleWorkspaceIdWorkflowIdNodesRoute:
      LocaleWorkspaceIdWorkflowIdNodesRoute,
    LocaleWorkspaceIdWorkflowIdReviewRoute:
      LocaleWorkspaceIdWorkflowIdReviewRoute,
    LocaleWorkspaceIdWorkflowIdSchemaRoute:
      LocaleWorkspaceIdWorkflowIdSchemaRoute,
    LocaleWorkspaceIdWorkflowIdIndexRoute:
      LocaleWorkspaceIdWorkflowIdIndexRoute,
    LocaleWorkspaceIdWorkflowIdTestsTestIdRoute:
      LocaleWorkspaceIdWorkflowIdTestsTestIdRoute,
    LocaleWorkspaceIdWorkflowIdTestsIndexRoute:
      LocaleWorkspaceIdWorkflowIdTestsIndexRoute,
  }

const LocaleWorkspaceIdWorkflowIdRouteRouteWithChildren =
  LocaleWorkspaceIdWorkflowIdRouteRoute._addFileChildren(
    LocaleWorkspaceIdWorkflowIdRouteRouteChildren,
  )

interface LocaleRouteRouteChildren {
  LocaleDemoRoute: typeof LocaleDemoRoute
  LocaleSettingsRoute: typeof LocaleSettingsRoute
  LocaleSetupRoute: typeof LocaleSetupRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleWorkspaceIdWorkflowIdRouteRoute: typeof LocaleWorkspaceIdWorkflowIdRouteRouteWithChildren
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleDemoRoute: LocaleDemoRoute,
  LocaleSettingsRoute: LocaleSettingsRoute,
  LocaleSetupRoute: LocaleSetupRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleWorkspaceIdWorkflowIdRouteRoute:
    LocaleWorkspaceIdWorkflowIdRouteRouteWithChildren,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
