"""Generate the published API reference from the installed AQVEN Python package.

Run with a Python environment that has this checkout's aqven package installed:
    python tools/generate_reference.py
    python tools/generate_reference.py --check
"""

from __future__ import annotations

import annotationlib
import argparse
import dataclasses
import enum
import importlib
import inspect
import json
import sys
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from pathlib import Path
from typing import Any, Final, TypeAliasType, cast, get_args, get_origin

from pydantic import BaseModel

import aqven
from aqven.cli import COMMANDS
from aqven.console.command import EXIT_FAILED, EXIT_OK, EXIT_USAGE
from aqven.console.series import STATUS_EXITS, USAGE_CODES
from aqven.diagnostics import DIAGNOSTIC_TEXTS, RULE_BY_CODE, SEVERITY_BY_CODE, DiagnosticCode
from aqven.engine.control.outcomes import ControlErrorCode
from aqven.engine.llm.errors import LlmFailureCode
from aqven.engine.policies.errors import PolicyErrorCode
from aqven.loader import LoadedExperiment, load_project
from aqven.policies import BUILTINS
from aqven.runtime.vocabulary import MODEL_OUTPUT_ERROR_CODES, AttemptCauseKind, ExecutionStatus, RunStatus
from aqven.series.facts import OUTCOME_BY_CODE
from aqven.series.model import (
    COUNTED_OUTCOMES,
    SETTLED_STATUSES,
    TERMINAL_STATUSES,
    ApprovalReason,
    AttemptOutcome,
    DegenerateReason,
    OutcomeClass,
    RecommendationReason,
    SeriesStatus,
)
from aqven.series.protocol import APPROVAL_THRESHOLD, INFRA_ERROR_LIMIT
from aqven.series.scoring import SKIP_RULES, SkipRule, failed_without_output, run_it, skip_all
from aqven.server.errors import HTTP_STATUS, ApiErrorCode
from aqven.spec import CellVerdict, FactorKind, VerdictReason, VerdictState
from aqven.spec.common import SpecModel
from aqven_llm import PROVIDERS

REPO_ROOT = Path(__file__).resolve().parents[1]
SITE = REPO_ROOT / "apps/site"
DOCS = SITE / "src/content/docs/reference"
ENGINE_DOCS = SITE / "src/content/docs/engine"
SCHEMAS = SITE / "public/reference/schemas"
LUMEN = REPO_ROOT / "examples/lumen"
GENERATED_NOTE: Final = "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->"
GROUPS = {
    "project": ("Project configuration", "aqven.spec.project"),
    "flows": ("Flow specification", "aqven.spec.flow"),
    "nodes": ("Node specifications", "aqven.spec.nodes"),
    "fields": ("Fields and bindings", "aqven.spec.fields"),
    "inference": ("Inference specification", "aqven.spec.inference"),
    "agents": ("Agent specification", "aqven.spec.agent"),
    "tools": ("Tool specification", "aqven.spec.tool"),
    "types": ("Type specifications", "aqven.spec.types"),
    "datasets": ("Datasets", "aqven.spec.datasets"),
    "experiments": ("Experiments", "aqven.spec.experiments"),
    "findings": ("Findings", "aqven.spec.findings"),
    "policies": ("Policies and limits", "aqven.spec.policy"),
    "common": ("Common limits and constraints", "aqven.spec.common"),
    "media": ("Media and dynamic values", "aqven.spec.builtins"),
    "mcp": ("MCP servers", "aqven.spec.mcp"),
    "prompts": ("Rendered prompts", "aqven.spec.prompts"),
}
MODEL_ORDER = {
    "aqven.spec.nodes": (
        "LlmNodeSpec",
        "CodeNodeSpec",
        "ToolNodeSpec",
        "HumanNodeSpec",
        "ParallelNodeSpec",
        "MapNodeSpec",
        "SwitchNodeSpec",
        "SwitchCase",
        "LoopNodeSpec",
        "CallNodeSpec",
        "NarrowNodeSpec",
    ),
    "aqven.spec.types": (
        "RecordType",
        "EnumType",
        "UnionType",
        "UnionVariant",
        "IdType",
        "ValueType",
        "EnumValue",
    ),
}


def type_text(schema: dict[str, Any], defs: dict[str, Any] | None = None) -> str:
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        definition = (defs or {}).get(name, {})
        if "enum" in definition:
            return " | ".join(repr(value) for value in definition["enum"])
        return name
    if "const" in schema:
        return repr(schema["const"])
    if "enum" in schema:
        return " | ".join(repr(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(type_text(part, defs) for part in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(type_text(part, defs) for part in schema["oneOf"])
    if schema.get("type") == "array":
        item = type_text(schema.get("items", {}), defs)
        return f"({item})[]" if " | " in item else f"{item}[]"
    if schema.get("type") == "object":
        if "additionalProperties" in schema:
            return f"map<string, {type_text(schema['additionalProperties'], defs)}>"
        return "object"
    return str(schema.get("type", "any"))


def constraints_text(schema: dict[str, Any]) -> str:
    keys = (
        "minLength",
        "maxLength",
        "minItems",
        "maxItems",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "pattern",
    )
    return ", ".join(f"{key}={schema[key]}" for key in keys if key in schema) or "—"


def clean(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def machine_independent(text: str) -> str:
    return text.replace(sys.executable, "sys.executable")


def default_text(model: type[BaseModel], alias: str, schema_field: dict[str, Any]) -> str:
    if "default" in schema_field:
        return repr(schema_field["default"])
    field = next(
        (field for field in model.model_fields.values() if (field.alias or field.validation_alias) == alias),
        None,
    )
    if field is None:
        field = model.model_fields.get(alias)
    factory = field.default_factory if field is not None else None
    if factory is list or get_origin(factory) is list:
        return "[]"
    if factory is dict or get_origin(factory) is dict:
        return "{}"
    return "not set"


def model_section(model: type[BaseModel]) -> str:
    schema = model.model_json_schema(by_alias=True)
    defs = schema.get("$defs", {})
    required = set(schema.get("required", []))
    rows = [
        f"## {model.__name__}",
        "",
        "| YAML field | Type | Required | Default | Constraints |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name, field in schema.get("properties", {}).items():
        default = "—" if name in required else clean(default_text(model, name, field))
        rows.append(
            f"| `{name}` | `{clean(type_text(field, defs))}` | {'Yes' if name in required else 'No'} | `{default}` | {clean(constraints_text(field))} |"
        )
    rows.extend(("", f"[JSON Schema](/reference/schemas/{model.__name__}.json)", ""))
    return "\n".join(rows)


def spec_page(title: str, module_name: str) -> tuple[str, dict[str, str]]:
    module = importlib.import_module(module_name)
    discovered = {
        value.__name__: value
        for value in vars(module).values()
        if inspect.isclass(value)
        and issubclass(value, BaseModel)
        and value not in (BaseModel, SpecModel)
        and value.__module__ == module_name
    }
    models = (
        [discovered[name] for name in MODEL_ORDER[module_name]]
        if module_name in MODEL_ORDER
        else sorted(discovered.values(), key=lambda model: model.__name__)
    )
    header = (
        f"---\ntitle: {title}\ndescription: Generated field reference from the AQVEN Python package.\n---\n\n"
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->\n\n"
        "This reference is generated from the package's Pydantic models. Fields use their YAML aliases. "
        "Unknown fields are rejected. Cross-field rules implemented by validators may not appear in JSON Schema; "
        "run `{{CLI_COMMAND}} check` on a complete project.\n\n"
    )
    schemas = {
        model.__name__: json.dumps(model.model_json_schema(by_alias=True), indent=2, sort_keys=True) + "\n"
        for model in models
    }
    return header + "\n".join(model_section(model) for model in models), schemas


def public_callable(member: object) -> Callable[..., object] | None:
    if isinstance(member, (classmethod, staticmethod)):
        wrapper = cast("classmethod[Any, ..., Any] | staticmethod[..., Any]", member)
        return cast(Callable[..., object], wrapper.__func__)
    if inspect.isfunction(member):
        return cast(Callable[..., object], member)
    return None


def public_methods(owner: type) -> list[tuple[str, Callable[..., object]]]:
    members = cast(dict[str, object], vars(owner))
    found: list[tuple[str, Callable[..., object]]] = []
    for member_name, member in members.items():
        if member_name.startswith("_"):
            continue
        method = public_callable(member)
        if method is None:
            continue
        found.append((member_name, method))
    return found


def api_page() -> str:
    lines = [
        "---",
        "title: Python API",
        "description: Generated signatures of the public AQVEN Python package.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "The names below come from `aqven.__all__`. Import them from `aqven`. Signatures reflect the installed package used to generate this page.",
        "",
    ]
    for name in sorted(aqven.__all__):
        value = getattr(aqven, name)
        lines.extend((f"## {name}", ""))
        if inspect.isclass(value):
            lines.append(f"`class {name}` · `{value.__module__}`")
            lines.append("")
            if issubclass(value, BaseModel):
                schema = value.model_json_schema(by_alias=True)
                required = set(schema.get("required", []))
                properties = schema.get("properties", {})
                if properties:
                    lines.extend(
                        (
                            "| Field | Type | Required | Default |",
                            "| --- | --- | --- | --- |",
                        )
                    )
                    for field_name, field in properties.items():
                        default = "—" if field_name in required else clean(default_text(value, field_name, field))
                        lines.append(
                            f"| `{field_name}` | `{clean(type_text(field, schema.get('$defs', {})))}` | {'Yes' if field_name in required else 'No'} | `{default}` |"
                        )
                    lines.append("")
            elif dataclasses.is_dataclass(value):
                fields = dataclasses.fields(value)
                if fields:
                    lines.extend(("| Field | Type | Default |", "| --- | --- | --- |"))
                    for field in fields:
                        default = (
                            "—"
                            if field.default is dataclasses.MISSING and field.default_factory is dataclasses.MISSING
                            else "factory"
                            if field.default_factory is not dataclasses.MISSING
                            else repr(field.default)
                        )
                        lines.append(f"| `{field.name}` | `{clean(field.type)}` | `{clean(default)}` |")
                    lines.append("")
            for method_name, method in public_methods(value):
                try:
                    signature = inspect.signature(method, annotation_format=annotationlib.Format.STRING)
                except TypeError, ValueError:
                    continue
                prefix = (
                    "async def" if inspect.iscoroutinefunction(method) or inspect.isasyncgenfunction(method) else "def"
                )
                lines.append(machine_independent(f"- `{prefix} {method_name}{signature}`"))
            lines.append("")
        elif callable(value):
            try:
                prefix = "async def" if inspect.iscoroutinefunction(value) else "def"
                signature = inspect.signature(value, annotation_format=annotationlib.Format.STRING)
                lines.extend(
                    (
                        machine_independent(f"`{prefix} {name}{signature}`"),
                        "",
                    )
                )
            except TypeError, ValueError:
                pass
        summary = (value.__doc__ or "").split("\n\n", 1)[0].replace("\n", " ")
        if summary and len(summary) < 400 and not summary.startswith(f"{name}("):
            lines.extend((summary, ""))
    return "\n".join(lines) + "\n"


def enums_page() -> str:
    module = importlib.import_module("aqven.spec.names")
    lines = [
        "---",
        "title: Accepted values",
        "description: Generated enums from the AQVEN Python package.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "These values come from enum classes in `aqven.spec.names`.",
        "",
    ]
    for name, value in sorted(vars(module).items()):
        if not inspect.isclass(value) or not issubclass(value, enum.Enum) or value.__module__ != module.__name__:
            continue
        lines.extend((f"## {name}", "", "| Value |", "| --- |"))
        lines.extend(f"| `{member.value}` |" for member in value)
        lines.append("")
    return "\n".join(lines) + "\n"


def policy_param_models() -> list[type[BaseModel]]:
    models: list[type[BaseModel]] = []
    for module_name in (
        "aqven.policies.contracts",
        "aqven.policies.control",
        "aqven.policies.evaluators",
    ):
        module = importlib.import_module(module_name)
        models.extend(
            value
            for value in vars(module).values()
            if inspect.isclass(value)
            and issubclass(value, BaseModel)
            and value.__module__ == module_name
            and value.__name__.endswith("Params")
        )
    return sorted(models, key=lambda model: model.__name__)


def builtins_page() -> tuple[str, dict[str, str]]:
    lines = [
        "---",
        "title: Built-in policies and evaluators",
        "description: Generated policy names and Python signatures.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "Use these names with `use:` in a policy or evaluator slot. The accepted `with:` keys follow each Python signature; run `{{CLI_COMMAND}} check` to validate the slot and parameters.",
        "",
        "None of these fit your check? [How to write a custom evaluator](/engine/custom-evaluator/) covers "
        "writing your own with `run:` instead of `use:` — same signature shape as every `evaluator` row below.",
        "",
    ]
    for slot, members in BUILTINS.items():
        lines.extend(
            (
                f"## {slot.value}",
                "",
                "| `use` name | Python signature |",
                "| --- | --- |",
            )
        )
        for name, function in members.items():
            signature = inspect.signature(function, annotation_format=annotationlib.Format.STRING)
            lines.append(f"| `{name}` | `{machine_independent(clean(f'{function.__name__}{signature}'))}` |")
        lines.append("")
    lines.extend(("## `with` parameter models", ""))
    models = policy_param_models()
    lines.extend(model_section(model) for model in models)
    schemas = {
        model.__name__: json.dumps(model.model_json_schema(by_alias=True), indent=2, sort_keys=True) + "\n"
        for model in models
    }
    return "\n".join(lines) + "\n", schemas


def provider_catalog_page() -> str:
    lines = [
        "---",
        "title: Provider catalog",
        "description: Generated catalog of model providers in the installed Python package.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "These providers come from `{{LLM_PYTHON_MODULE}}.catalog.PROVIDERS`. The key column names the default environment variable; project `api_key` may point to another environment variable. A provider's presence in the catalog does not guarantee that a particular model supports every modality or output mode. Use `{{CLI_COMMAND}} models check --project .` and `--live` when a real request is needed.",
        "",
        "| Provider prefix | Pydantic AI model class | Default key variable | Required | Extra |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name, entry in PROVIDERS.items():
        key = entry.key.primary or "—"
        extra = entry.extra.name if entry.extra is not None else "—"
        lines.append(
            f"| `{name}` | `{entry.model_class.qualified}` | `{key}` | {'Yes' if entry.key.required else 'No'} | `{extra}` |"
        )
    lines.extend(
        (
            "",
            "Choose a model with `<provider>:<model-name>` in an Agent file. The [provider guide](/integrations/model-providers/) shows complete project declarations and custom factories.",
            "",
        )
    )
    return "\n".join(lines)


def authoring_api_page() -> str:
    module = importlib.import_module("aqven.spec.builder")
    lines = [
        "---",
        "title: Python authoring API",
        "description: Generated signatures for Python flow and inference builders.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "Import these helpers from `{{PYTHON_MODULE}}.spec`. [How to write a step in Python](/engine/code-node/) shows complete files and when to use them.",
        "",
    ]
    for name in (
        "In",
        "Out",
        "inference_spec",
        "llm",
        "code",
        "tool",
        "flow",
        "describe_annotation",
    ):
        value = getattr(module, name)
        signature = inspect.signature(value, annotation_format=annotationlib.Format.STRING)
        lines.extend((f"## {name}", "", machine_independent(f"`def {name}{signature}`"), ""))
    for name in ("Inference", "Flow", "BuiltNode", "BuilderError"):
        value = getattr(module, name)
        lines.extend((f"## {name}", "", f"`class {name}` · `{value.__module__}`", ""))
        if dataclasses.is_dataclass(value):
            lines.extend(("| Field | Type |", "| --- | --- |"))
            lines.extend(f"| `{field.name}` | `{clean(field.type)}` |" for field in dataclasses.fields(value))
            lines.append("")
    return "\n".join(lines)


def cli_page() -> str:
    lines = [
        "---",
        "title: CLI commands",
        "description: Generated command registry from the AQVEN Python package.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "The command names and help text below come from `aqven.cli.COMMANDS`. Use `uv run {{CLI_COMMAND}} COMMAND --help` for the parser flags in the installed version.",
        "",
        "| Command | Help | Availability |",
        "| --- | --- | --- |",
    ]
    for name, command in COMMANDS.items():
        available = "Pending" if command.__class__.__name__ == "PendingCommand" else "Available"
        lines.append(f"| `{{{{CLI_COMMAND}}}} {name}` | {clean(command.help)} | {available} |")
    lines.extend(
        (
            "",
            "Pending commands are registered for future use but return `not implemented`; do not put them in automation. [How to check a project before committing](/engine/check/) shows a working command sequence.",
            "",
        )
    )
    return "\n".join(lines)


def openapi_page() -> str:
    document = json.loads((REPO_ROOT / "apps/studio/src/api/openapi.json").read_text())
    lines = [
        "---",
        "title: HTTP API / OpenAPI",
        "description: Generated endpoint index from Studio's OpenAPI document.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "This index is generated from `apps/studio/src/api/openapi.json`. The running project server exposes the raw contract at `/api/openapi.json`.",
        "",
        "| Method | Path | Operation ID |",
        "| --- | --- | --- |",
    ]
    for path, methods in document["paths"].items():
        for method, operation in methods.items():
            if method.upper() not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            lines.append(f"| `{method.upper()}` | `{path}` | `{operation.get('operationId', '—')}` |")
    return "\n".join(lines) + "\n"


def project_mcp_tools_page() -> str:
    source = Path(aqven.__file__).resolve().parent / "server/mcp"
    names: set[str] = set()
    for path in source.rglob("*.py"):
        text = path.read_text()
        names.update(__import__("re").findall(r'name="([a-z_]+)"', text))
    lines = [
        "---",
        "title: Project MCP tool reference",
        "description: Generated operation index from AQVEN's project MCP registrations.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "The project MCP operations below are discovered from the AQVEN package source. Each MCP client receives its exact input and output JSON Schema during tool discovery.",
        "",
        "| Tool |",
        "| --- |",
        *(f"| `{name}` |" for name in sorted(names)),
        "",
        "Start the bridge with `uv run {{CLI_COMMAND}} mcp .`. [How to connect AQVEN as an MCP server](/mcp-cli/connect-an-agent/) explains safe usage and verification.",
        "",
    ]
    return "\n".join(lines)


def diagnostics_page() -> str:
    lines = [
        "---",
        "title: Diagnostics and error codes",
        "description: Generated diagnostic-code index from the AQVEN Python package.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "Diagnostic codes and severity are generated from `aqven.diagnostics`. Some codes also include implementation-provided message text.",
        "",
        "| Code | Severity | Message template |",
        "| --- | --- | --- |",
    ]
    for code in DiagnosticCode:
        text = DIAGNOSTIC_TEXTS.get(code)
        message = clean(text.message) if text is not None else "—"
        lines.append(f"| `{code.value}` | `{SEVERITY_BY_CODE[code].value}` | {message} |")
    return "\n".join(lines) + "\n"


def environment_page() -> str:
    lines = [
        "---",
        "title: Environment variables",
        "description: Generated provider key-variable index from the installed AQVEN packages.",
        "---",
        "",
        "<!-- Generated by tools/generate_reference.py. Do not edit this file by hand. -->",
        "",
        "Project secrets use `ref:env/NAME`. The provider defaults below come from the installed provider catalog; a project may point `api_key` at a different environment variable.",
        "",
        "| Provider prefix | Default variable | Required |",
        "| --- | --- | --- |",
    ]
    for name, entry in PROVIDERS.items():
        lines.append(f"| `{name}` | `{entry.key.primary or '—'}` | {'Yes' if entry.key.required else 'No'} |")
    return "\n".join(lines) + "\n"


def front_matter(title: str, description: str, *intro: str) -> list[str]:
    return ["---", f"title: {title}", f"description: {description}", "---", "", GENERATED_NOTE, "", *intro]


def table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    return [
        f"| {' | '.join(header)} |",
        f"| {' | '.join('---' for _ in header)} |",
        *(f"| {' | '.join(row)} |" for row in rows),
        "",
    ]


def ticked(value: object) -> str:
    return f"`{value}`"


def literal_values(alias: TypeAliasType) -> tuple[str, ...]:
    return tuple(str(value) for value in get_args(alias.__value__))


def described[K](members: Iterable[K], meanings: Mapping[K, str]) -> list[tuple[K, str]]:
    missing = [member for member in members if member not in meanings]
    if missing:
        raise SystemExit(f"generate_reference.py has no meaning for {missing}: add one")
    return [(member, meanings[member]) for member in members]


RUN_ERROR_SOURCES: Final[tuple[tuple[str, tuple[str, ...]], ...]] = (
    ("step", tuple(code.value for code in LlmFailureCode)),
    ("model call", tuple(sorted(MODEL_OUTPUT_ERROR_CODES))),
    ("container step: parallel, map, loop", literal_values(ControlErrorCode)),
    ("policy or check function", literal_values(PolicyErrorCode)),
    ("run", tuple(OUTCOME_BY_CODE)),
)
UNLISTED_OUTCOME: Final = OutcomeClass.INFRA_ERROR
CHECK_EFFECTS: Final[Mapping[SkipRule, str]] = {
    run_it: "scored on the output",
    failed_without_output: "binary checks fail, other checks are skipped",
    skip_all: "skipped",
}


def run_error_origins() -> dict[str, str]:
    found: dict[str, str] = {}
    for source, codes in RUN_ERROR_SOURCES:
        found.update({code: source for code in codes if code not in found})
    return found


def outcome_row(code: str, source: str) -> tuple[str, str, str, str]:
    outcome = OUTCOME_BY_CODE.get(code, UNLISTED_OUTCOME)
    return ticked(code), source, ticked(outcome.value), CHECK_EFFECTS[SKIP_RULES[outcome]]


def error_codes_page() -> str:
    lines = front_matter(
        "Error codes",
        "Generated index of run error codes, API error codes and check diagnostics from the AQVEN Python package.",
        "Every code below comes from the AQVEN package: the enums of failed steps and runs, the table a series uses "
        "to count an attempt, the API error codes and the diagnostics of `{{CLI_COMMAND}} check`.",
        "",
        "## Run errors",
        "",
        "A failed run, step or series attempt carries one of these in `error.code`. The series outcome says how a "
        f"series counts the attempt; a code not listed here counts as `{UNLISTED_OUTCOME.value}`. When more than "
        f"{INFRA_ERROR_LIMIT:.0%} of a series' attempts end in `{OutcomeClass.INFRA_ERROR.value}`, its verdict is "
        f"`{VerdictState.INVALID.value}`.",
        "",
    )
    rows = (outcome_row(code, source) for code, source in run_error_origins().items())
    lines.extend(table(("Code", "Raised by", "Series outcome", "Checks of the attempt"), rows))
    lines.extend(
        (
            "## Causes of a model retry",
            "",
            "A retried or abandoned model call records one of these causes on the attempt of the step.",
            "",
        )
    )
    lines.extend(table(("Cause",), ((ticked(cause),) for cause in literal_values(AttemptCauseKind))))
    lines.extend(
        (
            "## API errors",
            "",
            "The project server answers a refused MCP tool call or REST request with one of these codes and the HTTP "
            "status below.",
            "",
        )
    )
    api_rows = ((ticked(code), str(HTTP_STATUS[cast(ApiErrorCode, code)])) for code in literal_values(ApiErrorCode))
    lines.extend(table(("Code", "HTTP status"), api_rows))
    lines.extend(
        (
            "## Check diagnostics",
            "",
            "`{{CLI_COMMAND}} check` reports these codes. A code without a template builds its message where it is "
            "found; the message names the file, the path and the fix.",
            "",
        )
    )
    lines.extend(table(("Code", "Severity", "Rule", "Message template", "Hint"), diagnostic_rows()))
    return "\n".join(lines)


def diagnostic_rows() -> Iterator[tuple[str, str, str, str, str]]:
    for code in DiagnosticCode:
        text = DIAGNOSTIC_TEXTS.get(code)
        message = clean(text.message) if text is not None else "—"
        hint = clean(text.hint) if text is not None and text.hint is not None else "—"
        yield ticked(code.value), ticked(SEVERITY_BY_CODE[code].value), RULE_BY_CODE.get(code, "—"), message, hint


SERIES_STATUS_MEANINGS: Final[Mapping[SeriesStatus, str]] = {
    SeriesStatus.AWAITING_APPROVAL: "waits for a person to decide on spend in Studio; `pause.reason` says why",
    SeriesStatus.RUNNING: "attempts are running",
    SeriesStatus.WAITING_HUMAN: "a running attempt waits for a person to answer the form of a `human` step",
    SeriesStatus.DONE: "every attempt has finished; the verdict is final",
    SeriesStatus.CANCELLED: "cancelled before every attempt finished; the verdict is `invalid`",
    SeriesStatus.FAILED: "the series itself failed; the verdict is `invalid`",
}
PAUSE_MEANINGS: Final[Mapping[ApprovalReason, str]] = {
    ApprovalReason.CAP_ABOVE_PROJECT: "the series was started with `cap_usd` above the project's spend cap; no attempt "
    "runs before a person approves",
    ApprovalReason.SPEND_NEAR_CAP: f"the series has spent {APPROVAL_THRESHOLD:.0%} of its cap; no new attempt starts "
    "before a person decides",
}
VERDICT_MEANINGS: Final[Mapping[VerdictState, str]] = {
    VerdictState.CONFIRMED: "every primary metric and guardrail passed",
    VerdictState.REFUTED: "a primary metric or a guardrail failed",
    VerdictState.INCONCLUSIVE: "neither; `reason` says why, for example `below_mde`",
    VerdictState.INVALID: "the series cannot answer the question: cancelled, failed, cut by the budget, inputs "
    "changed while it ran, too many infrastructure errors, or no data",
    VerdictState.SIGNAL: "a result on dev cases or from a judge that no experiment validated: evidence to act on, "
    "not a finding",
}
ATTEMPT_MEANINGS: Final[Mapping[AttemptOutcome, str]] = {
    AttemptOutcome.PASSED: "finished with outcome `ok` and every check passed",
    AttemptOutcome.FAILED: "finished with a counted outcome and did not pass",
    AttemptOutcome.ERROR: "finished with an outcome that is not counted, or stopped before it finished",
    AttemptOutcome.WAITING: "its run waits for a person",
    AttemptOutcome.RUNNING: "its run is running",
}


def outcome_codes(outcome: OutcomeClass) -> str:
    codes = [ticked(code) for code, found in OUTCOME_BY_CODE.items() if found is outcome]
    unlisted = ["any other error code"] if outcome is UNLISTED_OUTCOME else []
    return ", ".join((*codes, *unlisted)) or "—"


def exit_rows() -> Iterator[tuple[str, str]]:
    exits = sorted({*STATUS_EXITS.values(), EXIT_OK, EXIT_FAILED, EXIT_USAGE})
    for value in exits:
        statuses = [ticked(status.value) for status, code in STATUS_EXITS.items() if code == value]
        extra = {
            EXIT_FAILED: ["the command failed, for example the project server did not answer"],
            EXIT_USAGE: [f"the server refused the series: {', '.join(ticked(code) for code in sorted(USAGE_CODES))}"],
        }.get(value, [])
        yield str(value), "; ".join((*statuses, *extra))


def values_section(title: str, intro: str, values: Iterable[str]) -> list[str]:
    return [f"## {title}", "", intro, "", *table(("Value",), ((ticked(value),) for value in values))]


def status_page() -> str:
    lines = front_matter(
        "Statuses and verdicts",
        "Generated index of series statuses, pause reasons, verdicts, attempt outcomes and run statuses.",
        "The values below come from the enums of the AQVEN package. [How a series decides]"
        "(/concepts/how-a-series-decides/) explains how they are reached.",
        "",
        "## Series status",
        "",
        "`status` of a series. The command `{{CLI_COMMAND}} series` stops waiting at a settled status and exits "
        "with the code shown.",
        "",
    )
    status_rows = (
        (
            ticked(status.value),
            meaning,
            "yes" if status in TERMINAL_STATUSES else "no",
            "yes" if status in SETTLED_STATUSES else "no",
            str(STATUS_EXITS.get(status, "—")),
        )
        for status, meaning in described(SeriesStatus, SERIES_STATUS_MEANINGS)
    )
    lines.extend(table(("Status", "Meaning", "Final", "Settled", "Exit code"), status_rows))
    lines.extend(("## Pause reasons", "", "`pause.reason` of a series in `awaiting_approval`.", ""))
    pause_rows = ((ticked(reason.value), meaning) for reason, meaning in described(ApprovalReason, PAUSE_MEANINGS))
    lines.extend(table(("Reason", "Meaning"), pause_rows))
    lines.extend(("## Verdicts", "", "`verdict.state` of a series; a `look` has no verdict.", ""))
    verdict_rows = ((ticked(state.value), meaning) for state, meaning in described(VerdictState, VERDICT_MEANINGS))
    lines.extend(table(("Verdict", "Meaning"), verdict_rows))
    lines.extend(
        values_section(
            "Verdict reasons",
            "`verdict.reason`: why a verdict is not a plain answer.",
            (reason.value for reason in VerdictReason),
        )
    )
    lines.extend(
        (
            "## Attempt outcomes",
            "",
            "How a series counts one attempt. Counted outcomes enter the metrics of the checks; the others are "
            "infrastructure and do not.",
            "",
        )
    )
    outcome_rows = (
        (
            ticked(outcome.value),
            outcome_codes(outcome),
            "yes" if outcome in COUNTED_OUTCOMES else "no",
            CHECK_EFFECTS[SKIP_RULES[outcome]],
        )
        for outcome in OutcomeClass
    )
    lines.extend(table(("Outcome", "Error codes", "Counted", "Checks of the attempt"), outcome_rows))
    lines.extend(("## Attempt rows", "", "`outcome` of an attempt in the rows of a series.", ""))
    attempt_rows = ((ticked(item.value), meaning) for item, meaning in described(AttemptOutcome, ATTEMPT_MEANINGS))
    lines.extend(table(("Outcome", "Meaning"), attempt_rows))
    lines.extend(
        values_section(
            "Check cells",
            "`verdict` of one metric of one variant in the series matrix.",
            (cell.value for cell in CellVerdict),
        )
    )
    lines.extend(
        values_section(
            "Recommendation reasons",
            "`recommended.reason` in the launch plan of a series.",
            (reason.value for reason in RecommendationReason),
        )
    )
    lines.extend(
        values_section(
            "Degenerate estimates",
            "`degenerate` of an estimate that has no usable interval.",
            (reason.value for reason in DegenerateReason),
        )
    )
    lines.extend(values_section("Run status", "`status` of a run.", literal_values(RunStatus)))
    lines.extend(values_section("Step status", "`status` of one step of a run.", literal_values(ExecutionStatus)))
    lines.extend(("## Exit codes of `{{CLI_COMMAND}} series`", ""))
    lines.extend(table(("Exit code", "When"), exit_rows()))
    return "\n".join(lines)


LUMEN_PATTERNS: Final[tuple[tuple[str, str, tuple[str, ...]], ...]] = (
    (
        "A prompt variant slot and fragments",
        "The `revise` step declares the slot `lamp_guide` in its inference, renders it with "
        "`{{ variants.lamp_guide }}` in its prompt, and includes shared fragments. One variant file and one fragment "
        "follow.",
        (
            "flows/support_case/nodes/polish/revise.inference.yaml",
            "flows/support_case/nodes/polish/revise.prompt.md",
            "flows/support_case/nodes/polish/revise.variants/lamp_guide/mains.md",
            "fragments/untrusted_input.md",
        ),
    ),
    (
        "A map",
        "`vote` runs its body node once per item of the list in `over`; the body reads the item as `$item`.",
        ("flows/support_case/nodes/vote/vote.node.yaml", "flows/support_case/nodes/vote/ballot.node.yaml"),
    ),
    (
        "A parallel",
        "`judges` runs every node in `body` at once and joins them with its `join` policy; one branch and the join "
        "function follow.",
        (
            "flows/judge_panel/nodes/judges/judges.node.yaml",
            "flows/judge_panel/nodes/judges/deepseek.node.yaml",
            "flows/judge_panel/nodes/judges/judges.py",
        ),
    ),
    (
        "A call",
        "`panel` runs the flow `judge_panel` as one step; its output is that flow's output.",
        ("flows/support_case/nodes/panel/panel.node.yaml", "flows/judge_panel/flow.yaml"),
    ),
    (
        "A switch",
        "`route` runs a node or binds values for each value of `on`.",
        ("flows/support_case/nodes/route/route.node.yaml",),
    ),
)
LUMEN_FACTOR_EXAMPLES: Final[Mapping[FactorKind, str]] = {
    FactorKind.AGENT: "judge_panel_agents",
    FactorKind.PROMPT: "panel_judge_prompt",
    FactorKind.USE: "panel_merge_rule",
    FactorKind.FLOW: "panel_single_judge",
}
SKIPPED_EXPERIMENT_PARTS: Final = frozenset({"__pycache__", "findings", ".aqven"})
EXPERIMENT_NOTES: Final = "experiment.md"
EXPERIMENT_FILE: Final = "experiment.yaml"
FENCE_LANGUAGES: Final[Mapping[str, str]] = {".yaml": "yaml", ".yml": "yaml", ".py": "python", ".liquid": "liquid"}


def fenced(relative: str) -> list[str]:
    text = (LUMEN / relative).read_text(encoding="utf-8")
    language = FENCE_LANGUAGES.get(Path(relative).suffix, "liquid" if "{{" in text or "{%" in text else "text")
    fence = "````" if "```" in text else "```"
    return [f'{fence}{language} title="{relative}"', text.rstrip("\n"), fence, ""]


def lumen_experiments() -> Mapping[str, LoadedExperiment]:
    loaded = load_project(LUMEN).project
    if loaded is None:
        raise SystemExit(f"{LUMEN} does not load: run aqven check {LUMEN}")
    return {str(key): value for key, value in sorted(loaded.experiments.items())}


def factor_of(experiment: LoadedExperiment) -> str:
    factor = experiment.source.spec.varies
    return ticked(factor.what.value) if factor is not None else "none"


def experiment_row(experiment: LoadedExperiment) -> tuple[str, str, str, str]:
    spec = experiment.source.spec
    nodes = ", ".join(ticked(node) for node in spec.varies.nodes) if spec.varies is not None else "—"
    variants = ", ".join(ticked(variant.id) for variant in spec.variants)
    return ticked(experiment.experiment_id), factor_of(experiment), nodes, variants


def experiment_files(experiment: LoadedExperiment) -> list[str]:
    folder = LUMEN / experiment.folder
    files = (
        path.relative_to(LUMEN).as_posix()
        for path in sorted(folder.rglob("*"), key=lambda path: (path.name != EXPERIMENT_FILE, path))
        if path.is_file()
        and path.name != EXPERIMENT_NOTES
        and not SKIPPED_EXPERIMENT_PARTS.intersection(path.relative_to(folder).parts)
    )
    return [line for relative in files for line in fenced(relative)]


def factor_example(kind: FactorKind, experiments: Mapping[str, LoadedExperiment]) -> list[str]:
    experiment = experiments[LUMEN_FACTOR_EXAMPLES[kind]]
    if factor_of(experiment) != ticked(kind.value):
        raise SystemExit(f"{experiment.experiment_id} no longer varies {kind.value}: pick another example")
    return [f"### `{kind.value}`: `{experiment.experiment_id}`", "", *experiment_files(experiment)]


def lumen_patterns_page() -> str:
    experiments = lumen_experiments()
    lines = front_matter(
        "Patterns in the showcase",
        "Generated from the showcase project, file by file. A prompt variant slot, map, parallel, call and switch "
        "steps, and one experiment for each factor kind.",
        "Every file below is copied as it is from the showcase project, the project "
        "`{{CLI_COMMAND}} new my_project --template showcase` creates (`examples/lumen` in the AQVEN repository). "
        "Paths are relative to the package root. [Tested snippets](/engine/snippets/) has the same patterns in a "
        "smaller project.",
        "",
    )
    for title, intro, files in LUMEN_PATTERNS:
        lines.extend((f"## {title}", "", intro, ""))
        lines.extend(line for relative in files for line in fenced(relative))
    lines.extend(
        (
            "## Experiments by factor",
            "",
            "`varies.what` of every experiment in the showcase. `none` means the experiment declares no factor: it "
            "has one variant, or every variant runs the flow as written (an A/A experiment).",
            "",
        )
    )
    lines.extend(table(("Experiment", "Factor", "Nodes", "Variants"), map(experiment_row, experiments.values())))
    for kind in FactorKind:
        lines.extend(factor_example(kind, experiments))
    return "\n".join(lines).rstrip("\n") + "\n"


def outputs() -> dict[Path, str]:
    generated: dict[Path, str] = {}
    for slug, (title, module_name) in GROUPS.items():
        page, schemas = spec_page(title, module_name)
        generated[DOCS / f"{slug}.md"] = page
        for name, schema in schemas.items():
            generated[SCHEMAS / f"{name}.json"] = schema
    generated[DOCS / "python-api.md"] = api_page()
    generated[DOCS / "provider-catalog.md"] = provider_catalog_page()
    generated[DOCS / "authoring-api.md"] = authoring_api_page()
    generated[DOCS / "cli.md"] = cli_page()
    generated[DOCS / "openapi.md"] = openapi_page()
    generated[DOCS / "project-mcp-tools.md"] = project_mcp_tools_page()
    generated[DOCS / "diagnostics.md"] = diagnostics_page()
    generated[DOCS / "environment.md"] = environment_page()
    generated[DOCS / "accepted-values.md"] = enums_page()
    generated[DOCS / "error-codes.md"] = error_codes_page()
    generated[DOCS / "status-and-verdicts.md"] = status_page()
    generated[ENGINE_DOCS / "lumen-patterns.md"] = lumen_patterns_page()
    builtins, policy_schemas = builtins_page()
    generated[DOCS / "built-in-policies.md"] = builtins
    for name, schema in policy_schemas.items():
        generated[SCHEMAS / f"{name}.json"] = schema
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    stale: list[Path] = []
    generated = outputs()
    extra_schemas = set(SCHEMAS.glob("*.json")) - generated.keys()
    if args.check:
        stale.extend(sorted(extra_schemas))
    else:
        for path in extra_schemas:
            path.unlink()
    for path, content in generated.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Generated reference is stale:\n" + "\n".join(str(path) for path in stale))
        return 1
    print("Reference is current" if args.check else "Reference generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
