# Generated by aqven generate. DO NOT EDIT: changes are overwritten; edit the YAML and run aqven generate.
from typing import Annotated, Literal

from pydantic import BaseModel, Field, StringConstraints

from aqven.spec import GENERATED_CONFIG, Image, MapItemError

type Aspect = Literal["condition", "completeness", "safety"]


type Category = Literal["furniture", "electronics", "clothing"]


type Decision = Literal["publish", "fix", "reject"]


class Finding(BaseModel):
    model_config = GENERATED_CONFIG
    aspect: Aspect
    passed: bool
    note: Annotated[str, StringConstraints(max_length=300)]


class FixList(BaseModel):
    model_config = GENERATED_CONFIG
    message: Annotated[str, StringConstraints(max_length=600)]


class FixRequest(BaseModel):
    model_config = GENERATED_CONFIG
    title: Annotated[str, StringConstraints(max_length=120)]
    findings: Annotated[list[Finding], Field(max_length=3)]


class Listing(BaseModel):
    model_config = GENERATED_CONFIG
    title: Annotated[str, StringConstraints(max_length=120)]
    description: Annotated[str, StringConstraints(max_length=2000)]
    category: Category
    photos: Annotated[list[Image], Field(max_length=4)]


class Review(BaseModel):
    model_config = GENERATED_CONFIG
    decision: Decision
    message: Annotated[str, StringConstraints(max_length=600)]
    findings: Annotated[list[Finding], Field(max_length=3)]
    unread: Annotated[list[MapItemError], Field(max_length=3)]
    votes: Annotated[list[Decision], Field(max_length=3)]


class DecideIn(BaseModel):
    model_config = GENERATED_CONFIG
    title: Annotated[str, StringConstraints(max_length=120)]
    photos_match: bool
    findings: Annotated[list[Finding], Field(max_length=3)]


class DecideOut(BaseModel):
    model_config = GENERATED_CONFIG
    decision: Decision
    reason: Annotated[str, StringConstraints(max_length=300)]


class JudgeAspectIn(BaseModel):
    model_config = GENERATED_CONFIG
    aspect: Aspect
    description: Annotated[str, StringConstraints(max_length=2000)]
    photo_notes: Annotated[str, StringConstraints(max_length=600)]


class JudgeAspectOut(BaseModel):
    model_config = GENERATED_CONFIG
    finding: Finding


class MatchPhotosIn(BaseModel):
    model_config = GENERATED_CONFIG
    description: Annotated[str, StringConstraints(max_length=2000)]
    category: Category
    photos: Annotated[list[Image], Field(max_length=4)]


class MatchPhotosOut(BaseModel):
    model_config = GENERATED_CONFIG
    photo_notes: Annotated[str, StringConstraints(max_length=600)]
    photos_match: bool


class WriteIn(BaseModel):
    model_config = GENERATED_CONFIG
    title: Annotated[str, StringConstraints(max_length=120)]
    findings: Annotated[list[Finding], Field(max_length=3)]


class WriteOut(BaseModel):
    model_config = GENERATED_CONFIG
    message: Annotated[str, StringConstraints(max_length=600)]


class WriteShortIn(BaseModel):
    model_config = GENERATED_CONFIG
    title: Annotated[str, StringConstraints(max_length=120)]
    findings: Annotated[list[Finding], Field(max_length=3)]


class WriteShortOut(BaseModel):
    model_config = GENERATED_CONFIG
    message: Annotated[str, StringConstraints(max_length=600)]


class ListingReviewPrepareIn(BaseModel):
    model_config = GENERATED_CONFIG
    title: Annotated[str, StringConstraints(max_length=120)]
    category: Category


class ListingReviewPrepareOut(BaseModel):
    model_config = GENERATED_CONFIG
    title: Annotated[str, StringConstraints(max_length=120)]
    aspects: Annotated[list[Aspect], Field(max_length=3)]


class ListingReviewTallyIn(BaseModel):
    model_config = GENERATED_CONFIG
    votes: Annotated[list[Decision], Field(max_length=3)]


class ListingReviewTallyOut(BaseModel):
    model_config = GENERATED_CONFIG
    decision: Decision


class TallyRuleAnyRejectIn(BaseModel):
    model_config = GENERATED_CONFIG
    votes: Annotated[list[Decision], Field(max_length=3)]


class TallyRuleAnyRejectOut(BaseModel):
    model_config = GENERATED_CONFIG
    decision: Decision
